// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface AuthResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.AuthResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string result_string = 1;</code>
   * @return The resultString.
   */
  java.lang.String getResultString();
  /**
   * <code>string result_string = 1;</code>
   * @return The bytes for resultString.
   */
  com.google.protobuf.ByteString
      getResultStringBytes();

  /**
   * <code>string reason_string = 2;</code>
   * @return The reasonString.
   */
  java.lang.String getReasonString();
  /**
   * <code>string reason_string = 2;</code>
   * @return The bytes for reasonString.
   */
  com.google.protobuf.ByteString
      getReasonStringBytes();

  /**
   * <code>bytes props_hash = 3;</code>
   * @return The propsHash.
   */
  com.google.protobuf.ByteString getPropsHash();

  /**
   * <code>int64 version_ttl = 4;</code>
   * @return The versionTtl.
   */
  long getVersionTtl();

  /**
   * <code>.server.AuthResult.Result result = 5;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.server.AuthResult.Result result = 5;</code>
   * @return The result.
   */
  com.halloapp.proto.server.AuthResult.Result getResult();

  /**
   * <code>.server.AuthResult.Reason reason = 6;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.server.AuthResult.Reason reason = 6;</code>
   * @return The reason.
   */
  com.halloapp.proto.server.AuthResult.Reason getReason();
}
