// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface CallCapabilitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.CallCapabilities)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * true if the initiator supports pre-answering the call
   * </pre>
   *
   * <code>bool pre_answer = 1;</code>
   * @return The preAnswer.
   */
  boolean getPreAnswer();

  /**
   * <pre>
   * true if the initiator supports CallSdp ice restart
   * </pre>
   *
   * <code>bool sdp_restart = 2;</code>
   * @return The sdpRestart.
   */
  boolean getSdpRestart();
}
