// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface ClientOtpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ClientOtpResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.server.ClientOtpResponse.Result result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.server.ClientOtpResponse.Result result = 1;</code>
   * @return The result.
   */
  com.halloapp.proto.server.ClientOtpResponse.Result getResult();

  /**
   * <code>.server.ClientOtpResponse.Reason reason = 2;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.server.ClientOtpResponse.Reason reason = 2;</code>
   * @return The reason.
   */
  com.halloapp.proto.server.ClientOtpResponse.Reason getReason();
}
