// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface ClientLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ClientLog)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .server.Count counts = 1;</code>
   */
  java.util.List<com.halloapp.proto.server.Count> 
      getCountsList();
  /**
   * <code>repeated .server.Count counts = 1;</code>
   */
  com.halloapp.proto.server.Count getCounts(int index);
  /**
   * <code>repeated .server.Count counts = 1;</code>
   */
  int getCountsCount();

  /**
   * <code>repeated .server.EventData events = 2;</code>
   */
  java.util.List<com.halloapp.proto.log_events.EventData> 
      getEventsList();
  /**
   * <code>repeated .server.EventData events = 2;</code>
   */
  com.halloapp.proto.log_events.EventData getEvents(int index);
  /**
   * <code>repeated .server.EventData events = 2;</code>
   */
  int getEventsCount();
}
