// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.ClientMode}
 */
public  final class ClientMode extends
    com.google.protobuf.GeneratedMessageLite<
        ClientMode, ClientMode.Builder> implements
    // @@protoc_insertion_point(message_implements:server.ClientMode)
    ClientModeOrBuilder {
  private ClientMode() {
  }
  /**
   * Protobuf enum {@code server.ClientMode.Mode}
   */
  public enum Mode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ACTIVE = 0;</code>
     */
    ACTIVE(0),
    /**
     * <code>PASSIVE = 1;</code>
     */
    PASSIVE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACTIVE = 0;</code>
     */
    public static final int ACTIVE_VALUE = 0;
    /**
     * <code>PASSIVE = 1;</code>
     */
    public static final int PASSIVE_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Mode valueOf(int value) {
      return forNumber(value);
    }

    public static Mode forNumber(int value) {
      switch (value) {
        case 0: return ACTIVE;
        case 1: return PASSIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Mode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Mode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Mode>() {
            @java.lang.Override
            public Mode findValueByNumber(int number) {
              return Mode.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ModeVerifier.INSTANCE;
    }

    private static final class ModeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ModeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Mode.forNumber(number) != null;
            }
          };

    private final int value;

    private Mode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.ClientMode.Mode)
  }

  public static final int MODE_FIELD_NUMBER = 1;
  private int mode_;
  /**
   * <code>.server.ClientMode.Mode mode = 1;</code>
   * @return The enum numeric value on the wire for mode.
   */
  @java.lang.Override
  public int getModeValue() {
    return mode_;
  }
  /**
   * <code>.server.ClientMode.Mode mode = 1;</code>
   * @return The mode.
   */
  @java.lang.Override
  public com.halloapp.proto.server.ClientMode.Mode getMode() {
    com.halloapp.proto.server.ClientMode.Mode result = com.halloapp.proto.server.ClientMode.Mode.forNumber(mode_);
    return result == null ? com.halloapp.proto.server.ClientMode.Mode.UNRECOGNIZED : result;
  }
  /**
   * <code>.server.ClientMode.Mode mode = 1;</code>
   * @param value The enum numeric value on the wire for mode to set.
   */
  private void setModeValue(int value) {
      mode_ = value;
  }
  /**
   * <code>.server.ClientMode.Mode mode = 1;</code>
   * @param value The mode to set.
   */
  private void setMode(com.halloapp.proto.server.ClientMode.Mode value) {
    mode_ = value.getNumber();
    
  }
  /**
   * <code>.server.ClientMode.Mode mode = 1;</code>
   */
  private void clearMode() {
    
    mode_ = 0;
  }

  public static com.halloapp.proto.server.ClientMode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ClientMode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ClientMode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ClientMode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.ClientMode prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.ClientMode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.ClientMode, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ClientMode)
      com.halloapp.proto.server.ClientModeOrBuilder {
    // Construct using com.halloapp.proto.server.ClientMode.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.server.ClientMode.Mode mode = 1;</code>
     * @return The enum numeric value on the wire for mode.
     */
    @java.lang.Override
    public int getModeValue() {
      return instance.getModeValue();
    }
    /**
     * <code>.server.ClientMode.Mode mode = 1;</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setModeValue(int value) {
      copyOnWrite();
      instance.setModeValue(value);
      return this;
    }
    /**
     * <code>.server.ClientMode.Mode mode = 1;</code>
     * @return The mode.
     */
    @java.lang.Override
    public com.halloapp.proto.server.ClientMode.Mode getMode() {
      return instance.getMode();
    }
    /**
     * <code>.server.ClientMode.Mode mode = 1;</code>
     * @param value The enum numeric value on the wire for mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(com.halloapp.proto.server.ClientMode.Mode value) {
      copyOnWrite();
      instance.setMode(value);
      return this;
    }
    /**
     * <code>.server.ClientMode.Mode mode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      copyOnWrite();
      instance.clearMode();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.ClientMode)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.ClientMode();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "mode_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.ClientMode> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.ClientMode.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.ClientMode>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.ClientMode)
  private static final com.halloapp.proto.server.ClientMode DEFAULT_INSTANCE;
  static {
    ClientMode defaultInstance = new ClientMode();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ClientMode.class, defaultInstance);
  }

  public static com.halloapp.proto.server.ClientMode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ClientMode> PARSER;

  public static com.google.protobuf.Parser<ClientMode> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

