// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface ContactHashOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ContactHash)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes hash = 1;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();
}
