// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface ContactSyncErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ContactSyncError)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 retry_after_secs = 1;</code>
   * @return The retryAfterSecs.
   */
  int getRetryAfterSecs();
}
