// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.ExpiryInfo}
 */
public  final class ExpiryInfo extends
    com.google.protobuf.GeneratedMessageLite<
        ExpiryInfo, ExpiryInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:server.ExpiryInfo)
    ExpiryInfoOrBuilder {
  private ExpiryInfo() {
  }
  /**
   * Protobuf enum {@code server.ExpiryInfo.ExpiryType}
   */
  public enum ExpiryType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>EXPIRES_IN_SECONDS = 0;</code>
     */
    EXPIRES_IN_SECONDS(0),
    /**
     * <code>NEVER = 1;</code>
     */
    NEVER(1),
    /**
     * <code>CUSTOM_DATE = 2;</code>
     */
    CUSTOM_DATE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EXPIRES_IN_SECONDS = 0;</code>
     */
    public static final int EXPIRES_IN_SECONDS_VALUE = 0;
    /**
     * <code>NEVER = 1;</code>
     */
    public static final int NEVER_VALUE = 1;
    /**
     * <code>CUSTOM_DATE = 2;</code>
     */
    public static final int CUSTOM_DATE_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExpiryType valueOf(int value) {
      return forNumber(value);
    }

    public static ExpiryType forNumber(int value) {
      switch (value) {
        case 0: return EXPIRES_IN_SECONDS;
        case 1: return NEVER;
        case 2: return CUSTOM_DATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExpiryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExpiryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExpiryType>() {
            @java.lang.Override
            public ExpiryType findValueByNumber(int number) {
              return ExpiryType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ExpiryTypeVerifier.INSTANCE;
    }

    private static final class ExpiryTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ExpiryTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ExpiryType.forNumber(number) != null;
            }
          };

    private final int value;

    private ExpiryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.ExpiryInfo.ExpiryType)
  }

  public static final int EXPIRY_TYPE_FIELD_NUMBER = 12;
  private int expiryType_;
  /**
   * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
   * @return The enum numeric value on the wire for expiryType.
   */
  @java.lang.Override
  public int getExpiryTypeValue() {
    return expiryType_;
  }
  /**
   * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
   * @return The expiryType.
   */
  @java.lang.Override
  public com.halloapp.proto.server.ExpiryInfo.ExpiryType getExpiryType() {
    com.halloapp.proto.server.ExpiryInfo.ExpiryType result = com.halloapp.proto.server.ExpiryInfo.ExpiryType.forNumber(expiryType_);
    return result == null ? com.halloapp.proto.server.ExpiryInfo.ExpiryType.UNRECOGNIZED : result;
  }
  /**
   * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
   * @param value The enum numeric value on the wire for expiryType to set.
   */
  private void setExpiryTypeValue(int value) {
      expiryType_ = value;
  }
  /**
   * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
   * @param value The expiryType to set.
   */
  private void setExpiryType(com.halloapp.proto.server.ExpiryInfo.ExpiryType value) {
    expiryType_ = value.getNumber();
    
  }
  /**
   * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
   */
  private void clearExpiryType() {
    
    expiryType_ = 0;
  }

  public static final int EXPIRES_IN_SECONDS_FIELD_NUMBER = 13;
  private long expiresInSeconds_;
  /**
   * <pre>
   * This is set when expiry_type is expires_in_sec.
   * </pre>
   *
   * <code>int64 expires_in_seconds = 13;</code>
   * @return The expiresInSeconds.
   */
  @java.lang.Override
  public long getExpiresInSeconds() {
    return expiresInSeconds_;
  }
  /**
   * <pre>
   * This is set when expiry_type is expires_in_sec.
   * </pre>
   *
   * <code>int64 expires_in_seconds = 13;</code>
   * @param value The expiresInSeconds to set.
   */
  private void setExpiresInSeconds(long value) {
    
    expiresInSeconds_ = value;
  }
  /**
   * <pre>
   * This is set when expiry_type is expires_in_sec.
   * </pre>
   *
   * <code>int64 expires_in_seconds = 13;</code>
   */
  private void clearExpiresInSeconds() {
    
    expiresInSeconds_ = 0L;
  }

  public static final int EXPIRY_TIMESTAMP_FIELD_NUMBER = 14;
  private long expiryTimestamp_;
  /**
   * <pre>
   * This is set when expiry_type is custom_date.
   * </pre>
   *
   * <code>int64 expiry_timestamp = 14;</code>
   * @return The expiryTimestamp.
   */
  @java.lang.Override
  public long getExpiryTimestamp() {
    return expiryTimestamp_;
  }
  /**
   * <pre>
   * This is set when expiry_type is custom_date.
   * </pre>
   *
   * <code>int64 expiry_timestamp = 14;</code>
   * @param value The expiryTimestamp to set.
   */
  private void setExpiryTimestamp(long value) {
    
    expiryTimestamp_ = value;
  }
  /**
   * <pre>
   * This is set when expiry_type is custom_date.
   * </pre>
   *
   * <code>int64 expiry_timestamp = 14;</code>
   */
  private void clearExpiryTimestamp() {
    
    expiryTimestamp_ = 0L;
  }

  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ExpiryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.ExpiryInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.ExpiryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.ExpiryInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ExpiryInfo)
      com.halloapp.proto.server.ExpiryInfoOrBuilder {
    // Construct using com.halloapp.proto.server.ExpiryInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
     * @return The enum numeric value on the wire for expiryType.
     */
    @java.lang.Override
    public int getExpiryTypeValue() {
      return instance.getExpiryTypeValue();
    }
    /**
     * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
     * @param value The expiryType to set.
     * @return This builder for chaining.
     */
    public Builder setExpiryTypeValue(int value) {
      copyOnWrite();
      instance.setExpiryTypeValue(value);
      return this;
    }
    /**
     * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
     * @return The expiryType.
     */
    @java.lang.Override
    public com.halloapp.proto.server.ExpiryInfo.ExpiryType getExpiryType() {
      return instance.getExpiryType();
    }
    /**
     * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
     * @param value The enum numeric value on the wire for expiryType to set.
     * @return This builder for chaining.
     */
    public Builder setExpiryType(com.halloapp.proto.server.ExpiryInfo.ExpiryType value) {
      copyOnWrite();
      instance.setExpiryType(value);
      return this;
    }
    /**
     * <code>.server.ExpiryInfo.ExpiryType expiry_type = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiryType() {
      copyOnWrite();
      instance.clearExpiryType();
      return this;
    }

    /**
     * <pre>
     * This is set when expiry_type is expires_in_sec.
     * </pre>
     *
     * <code>int64 expires_in_seconds = 13;</code>
     * @return The expiresInSeconds.
     */
    @java.lang.Override
    public long getExpiresInSeconds() {
      return instance.getExpiresInSeconds();
    }
    /**
     * <pre>
     * This is set when expiry_type is expires_in_sec.
     * </pre>
     *
     * <code>int64 expires_in_seconds = 13;</code>
     * @param value The expiresInSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setExpiresInSeconds(long value) {
      copyOnWrite();
      instance.setExpiresInSeconds(value);
      return this;
    }
    /**
     * <pre>
     * This is set when expiry_type is expires_in_sec.
     * </pre>
     *
     * <code>int64 expires_in_seconds = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiresInSeconds() {
      copyOnWrite();
      instance.clearExpiresInSeconds();
      return this;
    }

    /**
     * <pre>
     * This is set when expiry_type is custom_date.
     * </pre>
     *
     * <code>int64 expiry_timestamp = 14;</code>
     * @return The expiryTimestamp.
     */
    @java.lang.Override
    public long getExpiryTimestamp() {
      return instance.getExpiryTimestamp();
    }
    /**
     * <pre>
     * This is set when expiry_type is custom_date.
     * </pre>
     *
     * <code>int64 expiry_timestamp = 14;</code>
     * @param value The expiryTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setExpiryTimestamp(long value) {
      copyOnWrite();
      instance.setExpiryTimestamp(value);
      return this;
    }
    /**
     * <pre>
     * This is set when expiry_type is custom_date.
     * </pre>
     *
     * <code>int64 expiry_timestamp = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiryTimestamp() {
      copyOnWrite();
      instance.clearExpiryTimestamp();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.ExpiryInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.ExpiryInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "expiryType_",
            "expiresInSeconds_",
            "expiryTimestamp_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\f\u000e\u0003\u0000\u0000\u0000\f\f\r\u0002\u000e\u0002" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.ExpiryInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.ExpiryInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.ExpiryInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.ExpiryInfo)
  private static final com.halloapp.proto.server.ExpiryInfo DEFAULT_INSTANCE;
  static {
    ExpiryInfo defaultInstance = new ExpiryInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ExpiryInfo.class, defaultInstance);
  }

  public static com.halloapp.proto.server.ExpiryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ExpiryInfo> PARSER;

  public static com.google.protobuf.Parser<ExpiryInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

