// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.GeoTagResponse}
 */
public  final class GeoTagResponse extends
    com.google.protobuf.GeneratedMessageLite<
        GeoTagResponse, GeoTagResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:server.GeoTagResponse)
    GeoTagResponseOrBuilder {
  private GeoTagResponse() {
    geoTags_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * Protobuf enum {@code server.GeoTagResponse.Result}
   */
  public enum Result
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>FAIL = 1;</code>
     */
    FAIL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>FAIL = 1;</code>
     */
    public static final int FAIL_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    public static Result forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            @java.lang.Override
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ResultVerifier.INSTANCE;
    }

    private static final class ResultVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ResultVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Result.forNumber(number) != null;
            }
          };

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.GeoTagResponse.Result)
  }

  /**
   * Protobuf enum {@code server.GeoTagResponse.Reason}
   */
  public enum Reason
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>INVALID_REQUEST = 1;</code>
     */
    INVALID_REQUEST(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>INVALID_REQUEST = 1;</code>
     */
    public static final int INVALID_REQUEST_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Reason valueOf(int value) {
      return forNumber(value);
    }

    public static Reason forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return INVALID_REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Reason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Reason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Reason>() {
            @java.lang.Override
            public Reason findValueByNumber(int number) {
              return Reason.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ReasonVerifier.INSTANCE;
    }

    private static final class ReasonVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ReasonVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Reason.forNumber(number) != null;
            }
          };

    private final int value;

    private Reason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.GeoTagResponse.Reason)
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private int result_;
  /**
   * <code>.server.GeoTagResponse.Result result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  @java.lang.Override
  public int getResultValue() {
    return result_;
  }
  /**
   * <code>.server.GeoTagResponse.Result result = 1;</code>
   * @return The result.
   */
  @java.lang.Override
  public com.halloapp.proto.server.GeoTagResponse.Result getResult() {
    com.halloapp.proto.server.GeoTagResponse.Result result = com.halloapp.proto.server.GeoTagResponse.Result.forNumber(result_);
    return result == null ? com.halloapp.proto.server.GeoTagResponse.Result.UNRECOGNIZED : result;
  }
  /**
   * <code>.server.GeoTagResponse.Result result = 1;</code>
   * @param value The enum numeric value on the wire for result to set.
   */
  private void setResultValue(int value) {
      result_ = value;
  }
  /**
   * <code>.server.GeoTagResponse.Result result = 1;</code>
   * @param value The result to set.
   */
  private void setResult(com.halloapp.proto.server.GeoTagResponse.Result value) {
    result_ = value.getNumber();
    
  }
  /**
   * <code>.server.GeoTagResponse.Result result = 1;</code>
   */
  private void clearResult() {
    
    result_ = 0;
  }

  public static final int REASON_FIELD_NUMBER = 2;
  private int reason_;
  /**
   * <code>.server.GeoTagResponse.Reason reason = 2;</code>
   * @return The enum numeric value on the wire for reason.
   */
  @java.lang.Override
  public int getReasonValue() {
    return reason_;
  }
  /**
   * <code>.server.GeoTagResponse.Reason reason = 2;</code>
   * @return The reason.
   */
  @java.lang.Override
  public com.halloapp.proto.server.GeoTagResponse.Reason getReason() {
    com.halloapp.proto.server.GeoTagResponse.Reason result = com.halloapp.proto.server.GeoTagResponse.Reason.forNumber(reason_);
    return result == null ? com.halloapp.proto.server.GeoTagResponse.Reason.UNRECOGNIZED : result;
  }
  /**
   * <code>.server.GeoTagResponse.Reason reason = 2;</code>
   * @param value The enum numeric value on the wire for reason to set.
   */
  private void setReasonValue(int value) {
      reason_ = value;
  }
  /**
   * <code>.server.GeoTagResponse.Reason reason = 2;</code>
   * @param value The reason to set.
   */
  private void setReason(com.halloapp.proto.server.GeoTagResponse.Reason value) {
    reason_ = value.getNumber();
    
  }
  /**
   * <code>.server.GeoTagResponse.Reason reason = 2;</code>
   */
  private void clearReason() {
    
    reason_ = 0;
  }

  public static final int GEO_TAGS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> geoTags_;
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @return A list containing the geoTags.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getGeoTagsList() {
    return geoTags_;
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @return The count of geoTags.
   */
  @java.lang.Override
  public int getGeoTagsCount() {
    return geoTags_.size();
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @param index The index of the element to return.
   * @return The geoTags at the given index.
   */
  @java.lang.Override
  public java.lang.String getGeoTags(int index) {
    return geoTags_.get(index);
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the geoTags at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGeoTagsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        geoTags_.get(index));
  }
  private void ensureGeoTagsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        geoTags_;  if (!tmp.isModifiable()) {
      geoTags_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @param index The index to set the value at.
   * @param value The geoTags to set.
   */
  private void setGeoTags(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureGeoTagsIsMutable();
    geoTags_.set(index, value);
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @param value The geoTags to add.
   */
  private void addGeoTags(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureGeoTagsIsMutable();
    geoTags_.add(value);
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @param values The geoTags to add.
   */
  private void addAllGeoTags(
      java.lang.Iterable<java.lang.String> values) {
    ensureGeoTagsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, geoTags_);
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   */
  private void clearGeoTags() {
    geoTags_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string geo_tags = 3;</code>
   * @param value The bytes of the geoTags to add.
   */
  private void addGeoTagsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureGeoTagsIsMutable();
    geoTags_.add(value.toStringUtf8());
  }

  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.GeoTagResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.GeoTagResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.GeoTagResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.GeoTagResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.GeoTagResponse)
      com.halloapp.proto.server.GeoTagResponseOrBuilder {
    // Construct using com.halloapp.proto.server.GeoTagResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.server.GeoTagResponse.Result result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override
    public int getResultValue() {
      return instance.getResultValue();
    }
    /**
     * <code>.server.GeoTagResponse.Result result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResultValue(int value) {
      copyOnWrite();
      instance.setResultValue(value);
      return this;
    }
    /**
     * <code>.server.GeoTagResponse.Result result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public com.halloapp.proto.server.GeoTagResponse.Result getResult() {
      return instance.getResult();
    }
    /**
     * <code>.server.GeoTagResponse.Result result = 1;</code>
     * @param value The enum numeric value on the wire for result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(com.halloapp.proto.server.GeoTagResponse.Result value) {
      copyOnWrite();
      instance.setResult(value);
      return this;
    }
    /**
     * <code>.server.GeoTagResponse.Result result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }

    /**
     * <code>.server.GeoTagResponse.Reason reason = 2;</code>
     * @return The enum numeric value on the wire for reason.
     */
    @java.lang.Override
    public int getReasonValue() {
      return instance.getReasonValue();
    }
    /**
     * <code>.server.GeoTagResponse.Reason reason = 2;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonValue(int value) {
      copyOnWrite();
      instance.setReasonValue(value);
      return this;
    }
    /**
     * <code>.server.GeoTagResponse.Reason reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public com.halloapp.proto.server.GeoTagResponse.Reason getReason() {
      return instance.getReason();
    }
    /**
     * <code>.server.GeoTagResponse.Reason reason = 2;</code>
     * @param value The enum numeric value on the wire for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(com.halloapp.proto.server.GeoTagResponse.Reason value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>.server.GeoTagResponse.Reason reason = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }

    /**
     * <code>repeated string geo_tags = 3;</code>
     * @return A list containing the geoTags.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getGeoTagsList() {
      return java.util.Collections.unmodifiableList(
          instance.getGeoTagsList());
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @return The count of geoTags.
     */
    @java.lang.Override
    public int getGeoTagsCount() {
      return instance.getGeoTagsCount();
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @param index The index of the element to return.
     * @return The geoTags at the given index.
     */
    @java.lang.Override
    public java.lang.String getGeoTags(int index) {
      return instance.getGeoTags(index);
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the geoTags at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGeoTagsBytes(int index) {
      return instance.getGeoTagsBytes(index);
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @param index The index to set the value at.
     * @param value The geoTags to set.
     * @return This builder for chaining.
     */
    public Builder setGeoTags(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setGeoTags(index, value);
      return this;
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @param value The geoTags to add.
     * @return This builder for chaining.
     */
    public Builder addGeoTags(
        java.lang.String value) {
      copyOnWrite();
      instance.addGeoTags(value);
      return this;
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @param values The geoTags to add.
     * @return This builder for chaining.
     */
    public Builder addAllGeoTags(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllGeoTags(values);
      return this;
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGeoTags() {
      copyOnWrite();
      instance.clearGeoTags();
      return this;
    }
    /**
     * <code>repeated string geo_tags = 3;</code>
     * @param value The bytes of the geoTags to add.
     * @return This builder for chaining.
     */
    public Builder addGeoTagsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addGeoTagsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.GeoTagResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.GeoTagResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "result_",
            "reason_",
            "geoTags_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\f\u0002\f\u0003" +
              "\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.GeoTagResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.GeoTagResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.GeoTagResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.GeoTagResponse)
  private static final com.halloapp.proto.server.GeoTagResponse DEFAULT_INSTANCE;
  static {
    GeoTagResponse defaultInstance = new GeoTagResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GeoTagResponse.class, defaultInstance);
  }

  public static com.halloapp.proto.server.GeoTagResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GeoTagResponse> PARSER;

  public static com.google.protobuf.Parser<GeoTagResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

