// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface GetCallServersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.GetCallServers)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string call_id = 1;</code>
   * @return The callId.
   */
  java.lang.String getCallId();
  /**
   * <code>string call_id = 1;</code>
   * @return The bytes for callId.
   */
  com.google.protobuf.ByteString
      getCallIdBytes();

  /**
   * <code>int64 peer_uid = 2;</code>
   * @return The peerUid.
   */
  long getPeerUid();

  /**
   * <code>.server.CallType call_type = 3;</code>
   * @return The enum numeric value on the wire for callType.
   */
  int getCallTypeValue();
  /**
   * <code>.server.CallType call_type = 3;</code>
   * @return The callType.
   */
  com.halloapp.proto.server.CallType getCallType();
}
