// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface GroupFeedItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.GroupFeedItems)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string gid = 1;</code>
   * @return The gid.
   */
  java.lang.String getGid();
  /**
   * <code>string gid = 1;</code>
   * @return The bytes for gid.
   */
  com.google.protobuf.ByteString
      getGidBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string avatar_id = 3;</code>
   * @return The avatarId.
   */
  java.lang.String getAvatarId();
  /**
   * <code>string avatar_id = 3;</code>
   * @return The bytes for avatarId.
   */
  com.google.protobuf.ByteString
      getAvatarIdBytes();

  /**
   * <code>repeated .server.GroupFeedItem items = 4;</code>
   */
  java.util.List<com.halloapp.proto.server.GroupFeedItem> 
      getItemsList();
  /**
   * <code>repeated .server.GroupFeedItem items = 4;</code>
   */
  com.halloapp.proto.server.GroupFeedItem getItems(int index);
  /**
   * <code>repeated .server.GroupFeedItem items = 4;</code>
   */
  int getItemsCount();
}
