// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface GroupFeedHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.GroupFeedHistory)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string gid = 1;</code>
   * @return The gid.
   */
  java.lang.String getGid();
  /**
   * <code>string gid = 1;</code>
   * @return The bytes for gid.
   */
  com.google.protobuf.ByteString
      getGidBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>bytes payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <pre>
   * Serialized GroupFeedItems stanza and then encrypted using 1-1 channel.
   * </pre>
   *
   * <code>bytes enc_payload = 4;</code>
   * @return The encPayload.
   */
  com.google.protobuf.ByteString getEncPayload();

  /**
   * <code>bytes public_key = 5;</code>
   * @return The publicKey.
   */
  com.google.protobuf.ByteString getPublicKey();

  /**
   * <code>int32 one_time_pre_key_id = 6;</code>
   * @return The oneTimePreKeyId.
   */
  int getOneTimePreKeyId();

  /**
   * <pre>
   * Use &gt;=16 for temporary elements since 1-15 encode smaller
   * </pre>
   *
   * <code>string sender_log_info = 16;</code>
   * @return The senderLogInfo.
   */
  java.lang.String getSenderLogInfo();
  /**
   * <pre>
   * Use &gt;=16 for temporary elements since 1-15 encode smaller
   * </pre>
   *
   * <code>string sender_log_info = 16;</code>
   * @return The bytes for senderLogInfo.
   */
  com.google.protobuf.ByteString
      getSenderLogInfoBytes();

  /**
   * <pre>
   * ex: "HalloApp/Android0.127"
   * </pre>
   *
   * <code>string sender_client_version = 17;</code>
   * @return The senderClientVersion.
   */
  java.lang.String getSenderClientVersion();
  /**
   * <pre>
   * ex: "HalloApp/Android0.127"
   * </pre>
   *
   * <code>string sender_client_version = 17;</code>
   * @return The bytes for senderClientVersion.
   */
  com.google.protobuf.ByteString
      getSenderClientVersionBytes();
}
