// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.HistoryResend}
 */
public  final class HistoryResend extends
    com.google.protobuf.GeneratedMessageLite<
        HistoryResend, HistoryResend.Builder> implements
    // @@protoc_insertion_point(message_implements:server.HistoryResend)
    HistoryResendOrBuilder {
  private HistoryResend() {
    gid_ = "";
    id_ = "";
    receiverUids_ = emptyLongList();
    payload_ = com.google.protobuf.ByteString.EMPTY;
    encPayload_ = com.google.protobuf.ByteString.EMPTY;
    senderStateBundles_ = emptyProtobufList();
    encSenderState_ = com.google.protobuf.ByteString.EMPTY;
    audienceHash_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int GID_FIELD_NUMBER = 1;
  private java.lang.String gid_;
  /**
   * <code>string gid = 1;</code>
   * @return The gid.
   */
  @java.lang.Override
  public java.lang.String getGid() {
    return gid_;
  }
  /**
   * <code>string gid = 1;</code>
   * @return The bytes for gid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gid_);
  }
  /**
   * <code>string gid = 1;</code>
   * @param value The gid to set.
   */
  private void setGid(
      java.lang.String value) {
    value.getClass();
  
    gid_ = value;
  }
  /**
   * <code>string gid = 1;</code>
   */
  private void clearGid() {
    
    gid_ = getDefaultInstance().getGid();
  }
  /**
   * <code>string gid = 1;</code>
   * @param value The bytes for gid to set.
   */
  private void setGidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    gid_ = value.toStringUtf8();
    
  }

  public static final int ID_FIELD_NUMBER = 2;
  private java.lang.String id_;
  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 2;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    value.getClass();
  
    id_ = value;
  }
  /**
   * <code>string id = 2;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 2;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int SENDER_UID_FIELD_NUMBER = 3;
  private long senderUid_;
  /**
   * <code>int64 sender_uid = 3;</code>
   * @return The senderUid.
   */
  @java.lang.Override
  public long getSenderUid() {
    return senderUid_;
  }
  /**
   * <code>int64 sender_uid = 3;</code>
   * @param value The senderUid to set.
   */
  private void setSenderUid(long value) {
    
    senderUid_ = value;
  }
  /**
   * <code>int64 sender_uid = 3;</code>
   */
  private void clearSenderUid() {
    
    senderUid_ = 0L;
  }

  public static final int RECEIVER_UIDS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList receiverUids_;
  /**
   * <code>repeated int64 receiver_uids = 4;</code>
   * @return A list containing the receiverUids.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getReceiverUidsList() {
    return receiverUids_;
  }
  /**
   * <code>repeated int64 receiver_uids = 4;</code>
   * @return The count of receiverUids.
   */
  @java.lang.Override
  public int getReceiverUidsCount() {
    return receiverUids_.size();
  }
  /**
   * <code>repeated int64 receiver_uids = 4;</code>
   * @param index The index of the element to return.
   * @return The receiverUids at the given index.
   */
  @java.lang.Override
  public long getReceiverUids(int index) {
    return receiverUids_.getLong(index);
  }
  private int receiverUidsMemoizedSerializedSize = -1;
  private void ensureReceiverUidsIsMutable() {
    com.google.protobuf.Internal.LongList tmp = receiverUids_;
    if (!tmp.isModifiable()) {
      receiverUids_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int64 receiver_uids = 4;</code>
   * @param index The index to set the value at.
   * @param value The receiverUids to set.
   */
  private void setReceiverUids(
      int index, long value) {
    ensureReceiverUidsIsMutable();
    receiverUids_.setLong(index, value);
  }
  /**
   * <code>repeated int64 receiver_uids = 4;</code>
   * @param value The receiverUids to add.
   */
  private void addReceiverUids(long value) {
    ensureReceiverUidsIsMutable();
    receiverUids_.addLong(value);
  }
  /**
   * <code>repeated int64 receiver_uids = 4;</code>
   * @param values The receiverUids to add.
   */
  private void addAllReceiverUids(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureReceiverUidsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, receiverUids_);
  }
  /**
   * <code>repeated int64 receiver_uids = 4;</code>
   */
  private void clearReceiverUids() {
    receiverUids_ = emptyLongList();
  }

  public static final int PAYLOAD_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString payload_;
  /**
   * <code>bytes payload = 5;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }
  /**
   * <code>bytes payload = 5;</code>
   * @param value The payload to set.
   */
  private void setPayload(com.google.protobuf.ByteString value) {
    value.getClass();
  
    payload_ = value;
  }
  /**
   * <code>bytes payload = 5;</code>
   */
  private void clearPayload() {
    
    payload_ = getDefaultInstance().getPayload();
  }

  public static final int ENC_PAYLOAD_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString encPayload_;
  /**
   * <pre>
   * Encrypted payload using the group feed channel.
   * </pre>
   *
   * <code>bytes enc_payload = 6;</code>
   * @return The encPayload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncPayload() {
    return encPayload_;
  }
  /**
   * <pre>
   * Encrypted payload using the group feed channel.
   * </pre>
   *
   * <code>bytes enc_payload = 6;</code>
   * @param value The encPayload to set.
   */
  private void setEncPayload(com.google.protobuf.ByteString value) {
    value.getClass();
  
    encPayload_ = value;
  }
  /**
   * <pre>
   * Encrypted payload using the group feed channel.
   * </pre>
   *
   * <code>bytes enc_payload = 6;</code>
   */
  private void clearEncPayload() {
    
    encPayload_ = getDefaultInstance().getEncPayload();
  }

  public static final int SENDER_STATE_BUNDLES_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.server.SenderStateBundle> senderStateBundles_;
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.halloapp.proto.server.SenderStateBundle> getSenderStateBundlesList() {
    return senderStateBundles_;
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  public java.util.List<? extends com.halloapp.proto.server.SenderStateBundleOrBuilder> 
      getSenderStateBundlesOrBuilderList() {
    return senderStateBundles_;
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  @java.lang.Override
  public int getSenderStateBundlesCount() {
    return senderStateBundles_.size();
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.server.SenderStateBundle getSenderStateBundles(int index) {
    return senderStateBundles_.get(index);
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  public com.halloapp.proto.server.SenderStateBundleOrBuilder getSenderStateBundlesOrBuilder(
      int index) {
    return senderStateBundles_.get(index);
  }
  private void ensureSenderStateBundlesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.server.SenderStateBundle> tmp = senderStateBundles_;
    if (!tmp.isModifiable()) {
      senderStateBundles_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  private void setSenderStateBundles(
      int index, com.halloapp.proto.server.SenderStateBundle value) {
    value.getClass();
  ensureSenderStateBundlesIsMutable();
    senderStateBundles_.set(index, value);
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  private void addSenderStateBundles(com.halloapp.proto.server.SenderStateBundle value) {
    value.getClass();
  ensureSenderStateBundlesIsMutable();
    senderStateBundles_.add(value);
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  private void addSenderStateBundles(
      int index, com.halloapp.proto.server.SenderStateBundle value) {
    value.getClass();
  ensureSenderStateBundlesIsMutable();
    senderStateBundles_.add(index, value);
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  private void addAllSenderStateBundles(
      java.lang.Iterable<? extends com.halloapp.proto.server.SenderStateBundle> values) {
    ensureSenderStateBundlesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, senderStateBundles_);
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  private void clearSenderStateBundles() {
    senderStateBundles_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Sent by the sender.
   * </pre>
   *
   * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
   */
  private void removeSenderStateBundles(int index) {
    ensureSenderStateBundlesIsMutable();
    senderStateBundles_.remove(index);
  }

  public static final int ENC_SENDER_STATE_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString encSenderState_;
  /**
   * <pre>
   * Meant for the receiver, selected by the server from `sender_state_bundles`.
   * </pre>
   *
   * <code>bytes enc_sender_state = 8;</code>
   * @return The encSenderState.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncSenderState() {
    return encSenderState_;
  }
  /**
   * <pre>
   * Meant for the receiver, selected by the server from `sender_state_bundles`.
   * </pre>
   *
   * <code>bytes enc_sender_state = 8;</code>
   * @param value The encSenderState to set.
   */
  private void setEncSenderState(com.google.protobuf.ByteString value) {
    value.getClass();
  
    encSenderState_ = value;
  }
  /**
   * <pre>
   * Meant for the receiver, selected by the server from `sender_state_bundles`.
   * </pre>
   *
   * <code>bytes enc_sender_state = 8;</code>
   */
  private void clearEncSenderState() {
    
    encSenderState_ = getDefaultInstance().getEncSenderState();
  }

  public static final int AUDIENCE_HASH_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString audienceHash_;
  /**
   * <code>bytes audience_hash = 9;</code>
   * @return The audienceHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAudienceHash() {
    return audienceHash_;
  }
  /**
   * <code>bytes audience_hash = 9;</code>
   * @param value The audienceHash to set.
   */
  private void setAudienceHash(com.google.protobuf.ByteString value) {
    value.getClass();
  
    audienceHash_ = value;
  }
  /**
   * <code>bytes audience_hash = 9;</code>
   */
  private void clearAudienceHash() {
    
    audienceHash_ = getDefaultInstance().getAudienceHash();
  }

  public static com.halloapp.proto.server.HistoryResend parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.HistoryResend parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.HistoryResend parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.HistoryResend parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.HistoryResend prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.HistoryResend}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.HistoryResend, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.HistoryResend)
      com.halloapp.proto.server.HistoryResendOrBuilder {
    // Construct using com.halloapp.proto.server.HistoryResend.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string gid = 1;</code>
     * @return The gid.
     */
    @java.lang.Override
    public java.lang.String getGid() {
      return instance.getGid();
    }
    /**
     * <code>string gid = 1;</code>
     * @return The bytes for gid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGidBytes() {
      return instance.getGidBytes();
    }
    /**
     * <code>string gid = 1;</code>
     * @param value The gid to set.
     * @return This builder for chaining.
     */
    public Builder setGid(
        java.lang.String value) {
      copyOnWrite();
      instance.setGid(value);
      return this;
    }
    /**
     * <code>string gid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGid() {
      copyOnWrite();
      instance.clearGid();
      return this;
    }
    /**
     * <code>string gid = 1;</code>
     * @param value The bytes for gid to set.
     * @return This builder for chaining.
     */
    public Builder setGidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGidBytes(value);
      return this;
    }

    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>int64 sender_uid = 3;</code>
     * @return The senderUid.
     */
    @java.lang.Override
    public long getSenderUid() {
      return instance.getSenderUid();
    }
    /**
     * <code>int64 sender_uid = 3;</code>
     * @param value The senderUid to set.
     * @return This builder for chaining.
     */
    public Builder setSenderUid(long value) {
      copyOnWrite();
      instance.setSenderUid(value);
      return this;
    }
    /**
     * <code>int64 sender_uid = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderUid() {
      copyOnWrite();
      instance.clearSenderUid();
      return this;
    }

    /**
     * <code>repeated int64 receiver_uids = 4;</code>
     * @return A list containing the receiverUids.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getReceiverUidsList() {
      return java.util.Collections.unmodifiableList(
          instance.getReceiverUidsList());
    }
    /**
     * <code>repeated int64 receiver_uids = 4;</code>
     * @return The count of receiverUids.
     */
    @java.lang.Override
    public int getReceiverUidsCount() {
      return instance.getReceiverUidsCount();
    }
    /**
     * <code>repeated int64 receiver_uids = 4;</code>
     * @param index The index of the element to return.
     * @return The receiverUids at the given index.
     */
    @java.lang.Override
    public long getReceiverUids(int index) {
      return instance.getReceiverUids(index);
    }
    /**
     * <code>repeated int64 receiver_uids = 4;</code>
     * @param value The receiverUids to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverUids(
        int index, long value) {
      copyOnWrite();
      instance.setReceiverUids(index, value);
      return this;
    }
    /**
     * <code>repeated int64 receiver_uids = 4;</code>
     * @param value The receiverUids to add.
     * @return This builder for chaining.
     */
    public Builder addReceiverUids(long value) {
      copyOnWrite();
      instance.addReceiverUids(value);
      return this;
    }
    /**
     * <code>repeated int64 receiver_uids = 4;</code>
     * @param values The receiverUids to add.
     * @return This builder for chaining.
     */
    public Builder addAllReceiverUids(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllReceiverUids(values);
      return this;
    }
    /**
     * <code>repeated int64 receiver_uids = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverUids() {
      copyOnWrite();
      instance.clearReceiverUids();
      return this;
    }

    /**
     * <code>bytes payload = 5;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return instance.getPayload();
    }
    /**
     * <code>bytes payload = 5;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPayload(value);
      return this;
    }
    /**
     * <code>bytes payload = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      copyOnWrite();
      instance.clearPayload();
      return this;
    }

    /**
     * <pre>
     * Encrypted payload using the group feed channel.
     * </pre>
     *
     * <code>bytes enc_payload = 6;</code>
     * @return The encPayload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncPayload() {
      return instance.getEncPayload();
    }
    /**
     * <pre>
     * Encrypted payload using the group feed channel.
     * </pre>
     *
     * <code>bytes enc_payload = 6;</code>
     * @param value The encPayload to set.
     * @return This builder for chaining.
     */
    public Builder setEncPayload(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEncPayload(value);
      return this;
    }
    /**
     * <pre>
     * Encrypted payload using the group feed channel.
     * </pre>
     *
     * <code>bytes enc_payload = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncPayload() {
      copyOnWrite();
      instance.clearEncPayload();
      return this;
    }

    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    @java.lang.Override
    public java.util.List<com.halloapp.proto.server.SenderStateBundle> getSenderStateBundlesList() {
      return java.util.Collections.unmodifiableList(
          instance.getSenderStateBundlesList());
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    @java.lang.Override
    public int getSenderStateBundlesCount() {
      return instance.getSenderStateBundlesCount();
    }/**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.server.SenderStateBundle getSenderStateBundles(int index) {
      return instance.getSenderStateBundles(index);
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder setSenderStateBundles(
        int index, com.halloapp.proto.server.SenderStateBundle value) {
      copyOnWrite();
      instance.setSenderStateBundles(index, value);
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder setSenderStateBundles(
        int index, com.halloapp.proto.server.SenderStateBundle.Builder builderForValue) {
      copyOnWrite();
      instance.setSenderStateBundles(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder addSenderStateBundles(com.halloapp.proto.server.SenderStateBundle value) {
      copyOnWrite();
      instance.addSenderStateBundles(value);
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder addSenderStateBundles(
        int index, com.halloapp.proto.server.SenderStateBundle value) {
      copyOnWrite();
      instance.addSenderStateBundles(index, value);
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder addSenderStateBundles(
        com.halloapp.proto.server.SenderStateBundle.Builder builderForValue) {
      copyOnWrite();
      instance.addSenderStateBundles(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder addSenderStateBundles(
        int index, com.halloapp.proto.server.SenderStateBundle.Builder builderForValue) {
      copyOnWrite();
      instance.addSenderStateBundles(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder addAllSenderStateBundles(
        java.lang.Iterable<? extends com.halloapp.proto.server.SenderStateBundle> values) {
      copyOnWrite();
      instance.addAllSenderStateBundles(values);
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder clearSenderStateBundles() {
      copyOnWrite();
      instance.clearSenderStateBundles();
      return this;
    }
    /**
     * <pre>
     * Sent by the sender.
     * </pre>
     *
     * <code>repeated .server.SenderStateBundle sender_state_bundles = 7;</code>
     */
    public Builder removeSenderStateBundles(int index) {
      copyOnWrite();
      instance.removeSenderStateBundles(index);
      return this;
    }

    /**
     * <pre>
     * Meant for the receiver, selected by the server from `sender_state_bundles`.
     * </pre>
     *
     * <code>bytes enc_sender_state = 8;</code>
     * @return The encSenderState.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncSenderState() {
      return instance.getEncSenderState();
    }
    /**
     * <pre>
     * Meant for the receiver, selected by the server from `sender_state_bundles`.
     * </pre>
     *
     * <code>bytes enc_sender_state = 8;</code>
     * @param value The encSenderState to set.
     * @return This builder for chaining.
     */
    public Builder setEncSenderState(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEncSenderState(value);
      return this;
    }
    /**
     * <pre>
     * Meant for the receiver, selected by the server from `sender_state_bundles`.
     * </pre>
     *
     * <code>bytes enc_sender_state = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncSenderState() {
      copyOnWrite();
      instance.clearEncSenderState();
      return this;
    }

    /**
     * <code>bytes audience_hash = 9;</code>
     * @return The audienceHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAudienceHash() {
      return instance.getAudienceHash();
    }
    /**
     * <code>bytes audience_hash = 9;</code>
     * @param value The audienceHash to set.
     * @return This builder for chaining.
     */
    public Builder setAudienceHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAudienceHash(value);
      return this;
    }
    /**
     * <code>bytes audience_hash = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudienceHash() {
      copyOnWrite();
      instance.clearAudienceHash();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.HistoryResend)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.HistoryResend();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "gid_",
            "id_",
            "senderUid_",
            "receiverUids_",
            "payload_",
            "encPayload_",
            "senderStateBundles_",
            com.halloapp.proto.server.SenderStateBundle.class,
            "encSenderState_",
            "audienceHash_",
          };
          java.lang.String info =
              "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0002\u0000\u0001\u0208\u0002\u0208\u0003\u0002" +
              "\u0004%\u0005\n\u0006\n\u0007\u001b\b\n\t\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.HistoryResend> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.HistoryResend.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.HistoryResend>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.HistoryResend)
  private static final com.halloapp.proto.server.HistoryResend DEFAULT_INSTANCE;
  static {
    HistoryResend defaultInstance = new HistoryResend();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HistoryResend.class, defaultInstance);
  }

  public static com.halloapp.proto.server.HistoryResend getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HistoryResend> PARSER;

  public static com.google.protobuf.Parser<HistoryResend> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

