// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface IncomingCallPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.IncomingCallPush)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string call_id = 1;</code>
   * @return The callId.
   */
  java.lang.String getCallId();
  /**
   * <code>string call_id = 1;</code>
   * @return The bytes for callId.
   */
  com.google.protobuf.ByteString
      getCallIdBytes();

  /**
   * <code>.server.CallType call_type = 2;</code>
   * @return The enum numeric value on the wire for callType.
   */
  int getCallTypeValue();
  /**
   * <code>.server.CallType call_type = 2;</code>
   * @return The callType.
   */
  com.halloapp.proto.server.CallType getCallType();

  /**
   * <code>repeated .server.StunServer stun_servers = 3;</code>
   */
  java.util.List<com.halloapp.proto.server.StunServer> 
      getStunServersList();
  /**
   * <code>repeated .server.StunServer stun_servers = 3;</code>
   */
  com.halloapp.proto.server.StunServer getStunServers(int index);
  /**
   * <code>repeated .server.StunServer stun_servers = 3;</code>
   */
  int getStunServersCount();

  /**
   * <code>repeated .server.TurnServer turn_servers = 4;</code>
   */
  java.util.List<com.halloapp.proto.server.TurnServer> 
      getTurnServersList();
  /**
   * <code>repeated .server.TurnServer turn_servers = 4;</code>
   */
  com.halloapp.proto.server.TurnServer getTurnServers(int index);
  /**
   * <code>repeated .server.TurnServer turn_servers = 4;</code>
   */
  int getTurnServersCount();

  /**
   * <pre>
   * ts when message is generated by the server
   * </pre>
   *
   * <code>int64 timestamp_ms = 5;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();

  /**
   * <code>.server.CallConfig call_config = 6;</code>
   * @return Whether the callConfig field is set.
   */
  boolean hasCallConfig();
  /**
   * <code>.server.CallConfig call_config = 6;</code>
   * @return The callConfig.
   */
  com.halloapp.proto.server.CallConfig getCallConfig();
}
