// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * <pre>
 * Invitee Notice
 * </pre>
 *
 * Protobuf type {@code server.InviteeNotice}
 */
public  final class InviteeNotice extends
    com.google.protobuf.GeneratedMessageLite<
        InviteeNotice, InviteeNotice.Builder> implements
    // @@protoc_insertion_point(message_implements:server.InviteeNotice)
    InviteeNoticeOrBuilder {
  private InviteeNotice() {
    inviters_ = emptyProtobufList();
  }
  public static final int INVITERS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.server.Inviter> inviters_;
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.halloapp.proto.server.Inviter> getInvitersList() {
    return inviters_;
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  public java.util.List<? extends com.halloapp.proto.server.InviterOrBuilder> 
      getInvitersOrBuilderList() {
    return inviters_;
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  @java.lang.Override
  public int getInvitersCount() {
    return inviters_.size();
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.server.Inviter getInviters(int index) {
    return inviters_.get(index);
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  public com.halloapp.proto.server.InviterOrBuilder getInvitersOrBuilder(
      int index) {
    return inviters_.get(index);
  }
  private void ensureInvitersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.server.Inviter> tmp = inviters_;
    if (!tmp.isModifiable()) {
      inviters_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  private void setInviters(
      int index, com.halloapp.proto.server.Inviter value) {
    value.getClass();
  ensureInvitersIsMutable();
    inviters_.set(index, value);
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  private void addInviters(com.halloapp.proto.server.Inviter value) {
    value.getClass();
  ensureInvitersIsMutable();
    inviters_.add(value);
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  private void addInviters(
      int index, com.halloapp.proto.server.Inviter value) {
    value.getClass();
  ensureInvitersIsMutable();
    inviters_.add(index, value);
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  private void addAllInviters(
      java.lang.Iterable<? extends com.halloapp.proto.server.Inviter> values) {
    ensureInvitersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, inviters_);
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  private void clearInviters() {
    inviters_ = emptyProtobufList();
  }
  /**
   * <code>repeated .server.Inviter inviters = 1;</code>
   */
  private void removeInviters(int index) {
    ensureInvitersIsMutable();
    inviters_.remove(index);
  }

  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.InviteeNotice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.InviteeNotice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.InviteeNotice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.InviteeNotice prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Invitee Notice
   * </pre>
   *
   * Protobuf type {@code server.InviteeNotice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.InviteeNotice, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.InviteeNotice)
      com.halloapp.proto.server.InviteeNoticeOrBuilder {
    // Construct using com.halloapp.proto.server.InviteeNotice.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.halloapp.proto.server.Inviter> getInvitersList() {
      return java.util.Collections.unmodifiableList(
          instance.getInvitersList());
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    @java.lang.Override
    public int getInvitersCount() {
      return instance.getInvitersCount();
    }/**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.server.Inviter getInviters(int index) {
      return instance.getInviters(index);
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder setInviters(
        int index, com.halloapp.proto.server.Inviter value) {
      copyOnWrite();
      instance.setInviters(index, value);
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder setInviters(
        int index, com.halloapp.proto.server.Inviter.Builder builderForValue) {
      copyOnWrite();
      instance.setInviters(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder addInviters(com.halloapp.proto.server.Inviter value) {
      copyOnWrite();
      instance.addInviters(value);
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder addInviters(
        int index, com.halloapp.proto.server.Inviter value) {
      copyOnWrite();
      instance.addInviters(index, value);
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder addInviters(
        com.halloapp.proto.server.Inviter.Builder builderForValue) {
      copyOnWrite();
      instance.addInviters(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder addInviters(
        int index, com.halloapp.proto.server.Inviter.Builder builderForValue) {
      copyOnWrite();
      instance.addInviters(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder addAllInviters(
        java.lang.Iterable<? extends com.halloapp.proto.server.Inviter> values) {
      copyOnWrite();
      instance.addAllInviters(values);
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder clearInviters() {
      copyOnWrite();
      instance.clearInviters();
      return this;
    }
    /**
     * <code>repeated .server.Inviter inviters = 1;</code>
     */
    public Builder removeInviters(int index) {
      copyOnWrite();
      instance.removeInviters(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.InviteeNotice)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.InviteeNotice();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "inviters_",
            com.halloapp.proto.server.Inviter.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.InviteeNotice> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.InviteeNotice.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.InviteeNotice>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.InviteeNotice)
  private static final com.halloapp.proto.server.InviteeNotice DEFAULT_INSTANCE;
  static {
    InviteeNotice defaultInstance = new InviteeNotice();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InviteeNotice.class, defaultInstance);
  }

  public static com.halloapp.proto.server.InviteeNotice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InviteeNotice> PARSER;

  public static com.google.protobuf.Parser<InviteeNotice> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

