// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.NotificationPrefs}
 */
public  final class NotificationPrefs extends
    com.google.protobuf.GeneratedMessageLite<
        NotificationPrefs, NotificationPrefs.Builder> implements
    // @@protoc_insertion_point(message_implements:server.NotificationPrefs)
    NotificationPrefsOrBuilder {
  private NotificationPrefs() {
    pushPrefs_ = emptyProtobufList();
  }
  public static final int PUSH_PREFS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.server.PushPref> pushPrefs_;
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.halloapp.proto.server.PushPref> getPushPrefsList() {
    return pushPrefs_;
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  public java.util.List<? extends com.halloapp.proto.server.PushPrefOrBuilder> 
      getPushPrefsOrBuilderList() {
    return pushPrefs_;
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  @java.lang.Override
  public int getPushPrefsCount() {
    return pushPrefs_.size();
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.server.PushPref getPushPrefs(int index) {
    return pushPrefs_.get(index);
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  public com.halloapp.proto.server.PushPrefOrBuilder getPushPrefsOrBuilder(
      int index) {
    return pushPrefs_.get(index);
  }
  private void ensurePushPrefsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.server.PushPref> tmp = pushPrefs_;
    if (!tmp.isModifiable()) {
      pushPrefs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  private void setPushPrefs(
      int index, com.halloapp.proto.server.PushPref value) {
    value.getClass();
  ensurePushPrefsIsMutable();
    pushPrefs_.set(index, value);
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  private void addPushPrefs(com.halloapp.proto.server.PushPref value) {
    value.getClass();
  ensurePushPrefsIsMutable();
    pushPrefs_.add(value);
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  private void addPushPrefs(
      int index, com.halloapp.proto.server.PushPref value) {
    value.getClass();
  ensurePushPrefsIsMutable();
    pushPrefs_.add(index, value);
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  private void addAllPushPrefs(
      java.lang.Iterable<? extends com.halloapp.proto.server.PushPref> values) {
    ensurePushPrefsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, pushPrefs_);
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  private void clearPushPrefs() {
    pushPrefs_ = emptyProtobufList();
  }
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  private void removePushPrefs(int index) {
    ensurePushPrefsIsMutable();
    pushPrefs_.remove(index);
  }

  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.NotificationPrefs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.NotificationPrefs prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.NotificationPrefs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.NotificationPrefs, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.NotificationPrefs)
      com.halloapp.proto.server.NotificationPrefsOrBuilder {
    // Construct using com.halloapp.proto.server.NotificationPrefs.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.halloapp.proto.server.PushPref> getPushPrefsList() {
      return java.util.Collections.unmodifiableList(
          instance.getPushPrefsList());
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    @java.lang.Override
    public int getPushPrefsCount() {
      return instance.getPushPrefsCount();
    }/**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.server.PushPref getPushPrefs(int index) {
      return instance.getPushPrefs(index);
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder setPushPrefs(
        int index, com.halloapp.proto.server.PushPref value) {
      copyOnWrite();
      instance.setPushPrefs(index, value);
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder setPushPrefs(
        int index, com.halloapp.proto.server.PushPref.Builder builderForValue) {
      copyOnWrite();
      instance.setPushPrefs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder addPushPrefs(com.halloapp.proto.server.PushPref value) {
      copyOnWrite();
      instance.addPushPrefs(value);
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder addPushPrefs(
        int index, com.halloapp.proto.server.PushPref value) {
      copyOnWrite();
      instance.addPushPrefs(index, value);
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder addPushPrefs(
        com.halloapp.proto.server.PushPref.Builder builderForValue) {
      copyOnWrite();
      instance.addPushPrefs(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder addPushPrefs(
        int index, com.halloapp.proto.server.PushPref.Builder builderForValue) {
      copyOnWrite();
      instance.addPushPrefs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder addAllPushPrefs(
        java.lang.Iterable<? extends com.halloapp.proto.server.PushPref> values) {
      copyOnWrite();
      instance.addAllPushPrefs(values);
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder clearPushPrefs() {
      copyOnWrite();
      instance.clearPushPrefs();
      return this;
    }
    /**
     * <code>repeated .server.PushPref push_prefs = 1;</code>
     */
    public Builder removePushPrefs(int index) {
      copyOnWrite();
      instance.removePushPrefs(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.NotificationPrefs)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.NotificationPrefs();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "pushPrefs_",
            com.halloapp.proto.server.PushPref.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.NotificationPrefs> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.NotificationPrefs.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.NotificationPrefs>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.NotificationPrefs)
  private static final com.halloapp.proto.server.NotificationPrefs DEFAULT_INSTANCE;
  static {
    NotificationPrefs defaultInstance = new NotificationPrefs();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NotificationPrefs.class, defaultInstance);
  }

  public static com.halloapp.proto.server.NotificationPrefs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NotificationPrefs> PARSER;

  public static com.google.protobuf.Parser<NotificationPrefs> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

