// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface NotificationPrefsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.NotificationPrefs)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  java.util.List<com.halloapp.proto.server.PushPref> 
      getPushPrefsList();
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  com.halloapp.proto.server.PushPref getPushPrefs(int index);
  /**
   * <code>repeated .server.PushPref push_prefs = 1;</code>
   */
  int getPushPrefsCount();
}
