// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * <pre>
 * External Sharing
 * </pre>
 *
 * Protobuf type {@code server.OgTagInfo}
 */
public  final class OgTagInfo extends
    com.google.protobuf.GeneratedMessageLite<
        OgTagInfo, OgTagInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:server.OgTagInfo)
    OgTagInfoOrBuilder {
  private OgTagInfo() {
    title_ = "";
    description_ = "";
    thumbnailUrl_ = "";
  }
  public static final int TITLE_FIELD_NUMBER = 1;
  private java.lang.String title_;
  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string title = 1;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    title_ = value;
  }
  /**
   * <code>string title = 1;</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string title = 1;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();
    
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private java.lang.String description_;
  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 2;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 2;</code>
   */
  private void clearDescription() {
    
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 2;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();
    
  }

  public static final int THUMBNAIL_URL_FIELD_NUMBER = 3;
  private java.lang.String thumbnailUrl_;
  /**
   * <code>string thumbnail_url = 3;</code>
   * @return The thumbnailUrl.
   */
  @java.lang.Override
  public java.lang.String getThumbnailUrl() {
    return thumbnailUrl_;
  }
  /**
   * <code>string thumbnail_url = 3;</code>
   * @return The bytes for thumbnailUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThumbnailUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(thumbnailUrl_);
  }
  /**
   * <code>string thumbnail_url = 3;</code>
   * @param value The thumbnailUrl to set.
   */
  private void setThumbnailUrl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    thumbnailUrl_ = value;
  }
  /**
   * <code>string thumbnail_url = 3;</code>
   */
  private void clearThumbnailUrl() {
    
    thumbnailUrl_ = getDefaultInstance().getThumbnailUrl();
  }
  /**
   * <code>string thumbnail_url = 3;</code>
   * @param value The bytes for thumbnailUrl to set.
   */
  private void setThumbnailUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    thumbnailUrl_ = value.toStringUtf8();
    
  }

  public static final int THUMBNAIL_WIDTH_FIELD_NUMBER = 4;
  private int thumbnailWidth_;
  /**
   * <code>int32 thumbnail_width = 4;</code>
   * @return The thumbnailWidth.
   */
  @java.lang.Override
  public int getThumbnailWidth() {
    return thumbnailWidth_;
  }
  /**
   * <code>int32 thumbnail_width = 4;</code>
   * @param value The thumbnailWidth to set.
   */
  private void setThumbnailWidth(int value) {
    
    thumbnailWidth_ = value;
  }
  /**
   * <code>int32 thumbnail_width = 4;</code>
   */
  private void clearThumbnailWidth() {
    
    thumbnailWidth_ = 0;
  }

  public static final int THUMBNAIL_HEIGHT_FIELD_NUMBER = 5;
  private int thumbnailHeight_;
  /**
   * <code>int32 thumbnail_height = 5;</code>
   * @return The thumbnailHeight.
   */
  @java.lang.Override
  public int getThumbnailHeight() {
    return thumbnailHeight_;
  }
  /**
   * <code>int32 thumbnail_height = 5;</code>
   * @param value The thumbnailHeight to set.
   */
  private void setThumbnailHeight(int value) {
    
    thumbnailHeight_ = value;
  }
  /**
   * <code>int32 thumbnail_height = 5;</code>
   */
  private void clearThumbnailHeight() {
    
    thumbnailHeight_ = 0;
  }

  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.OgTagInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.OgTagInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.OgTagInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.OgTagInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * External Sharing
   * </pre>
   *
   * Protobuf type {@code server.OgTagInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.OgTagInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.OgTagInfo)
      com.halloapp.proto.server.OgTagInfoOrBuilder {
    // Construct using com.halloapp.proto.server.OgTagInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 2;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>string thumbnail_url = 3;</code>
     * @return The thumbnailUrl.
     */
    @java.lang.Override
    public java.lang.String getThumbnailUrl() {
      return instance.getThumbnailUrl();
    }
    /**
     * <code>string thumbnail_url = 3;</code>
     * @return The bytes for thumbnailUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getThumbnailUrlBytes() {
      return instance.getThumbnailUrlBytes();
    }
    /**
     * <code>string thumbnail_url = 3;</code>
     * @param value The thumbnailUrl to set.
     * @return This builder for chaining.
     */
    public Builder setThumbnailUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setThumbnailUrl(value);
      return this;
    }
    /**
     * <code>string thumbnail_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearThumbnailUrl() {
      copyOnWrite();
      instance.clearThumbnailUrl();
      return this;
    }
    /**
     * <code>string thumbnail_url = 3;</code>
     * @param value The bytes for thumbnailUrl to set.
     * @return This builder for chaining.
     */
    public Builder setThumbnailUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setThumbnailUrlBytes(value);
      return this;
    }

    /**
     * <code>int32 thumbnail_width = 4;</code>
     * @return The thumbnailWidth.
     */
    @java.lang.Override
    public int getThumbnailWidth() {
      return instance.getThumbnailWidth();
    }
    /**
     * <code>int32 thumbnail_width = 4;</code>
     * @param value The thumbnailWidth to set.
     * @return This builder for chaining.
     */
    public Builder setThumbnailWidth(int value) {
      copyOnWrite();
      instance.setThumbnailWidth(value);
      return this;
    }
    /**
     * <code>int32 thumbnail_width = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearThumbnailWidth() {
      copyOnWrite();
      instance.clearThumbnailWidth();
      return this;
    }

    /**
     * <code>int32 thumbnail_height = 5;</code>
     * @return The thumbnailHeight.
     */
    @java.lang.Override
    public int getThumbnailHeight() {
      return instance.getThumbnailHeight();
    }
    /**
     * <code>int32 thumbnail_height = 5;</code>
     * @param value The thumbnailHeight to set.
     * @return This builder for chaining.
     */
    public Builder setThumbnailHeight(int value) {
      copyOnWrite();
      instance.setThumbnailHeight(value);
      return this;
    }
    /**
     * <code>int32 thumbnail_height = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearThumbnailHeight() {
      copyOnWrite();
      instance.clearThumbnailHeight();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.OgTagInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.OgTagInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "title_",
            "description_",
            "thumbnailUrl_",
            "thumbnailWidth_",
            "thumbnailHeight_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0004\u0005\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.OgTagInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.OgTagInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.OgTagInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.OgTagInfo)
  private static final com.halloapp.proto.server.OgTagInfo DEFAULT_INSTANCE;
  static {
    OgTagInfo defaultInstance = new OgTagInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OgTagInfo.class, defaultInstance);
  }

  public static com.halloapp.proto.server.OgTagInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OgTagInfo> PARSER;

  public static com.google.protobuf.Parser<OgTagInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

