// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface PhoneElementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.PhoneElement)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.server.PhoneElement.Action action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.server.PhoneElement.Action action = 1;</code>
   * @return The action.
   */
  com.halloapp.proto.server.PhoneElement.Action getAction();

  /**
   * <code>string phone = 2;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 2;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
