// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface PostMetricsResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.PostMetricsResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.server.PostMetricsResult.Result result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.server.PostMetricsResult.Result result = 1;</code>
   * @return The result.
   */
  com.halloapp.proto.server.PostMetricsResult.Result getResult();

  /**
   * <code>.server.PostMetricsResult.Reason reason = 2;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.server.PostMetricsResult.Reason reason = 2;</code>
   * @return The reason.
   */
  com.halloapp.proto.server.PostMetricsResult.Reason getReason();

  /**
   * <code>.server.PostMetrics post_metrics = 3;</code>
   * @return Whether the postMetrics field is set.
   */
  boolean hasPostMetrics();
  /**
   * <code>.server.PostMetrics post_metrics = 3;</code>
   * @return The postMetrics.
   */
  com.halloapp.proto.server.PostMetrics getPostMetrics();
}
