// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface PublicFeedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.PublicFeedRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string cursor = 1;</code>
   * @return The cursor.
   */
  java.lang.String getCursor();
  /**
   * <code>string cursor = 1;</code>
   * @return The bytes for cursor.
   */
  com.google.protobuf.ByteString
      getCursorBytes();

  /**
   * <code>.server.PublicFeedContentType public_feed_content_type = 2;</code>
   * @return The enum numeric value on the wire for publicFeedContentType.
   */
  int getPublicFeedContentTypeValue();
  /**
   * <code>.server.PublicFeedContentType public_feed_content_type = 2;</code>
   * @return The publicFeedContentType.
   */
  com.halloapp.proto.server.PublicFeedContentType getPublicFeedContentType();

  /**
   * <code>.server.GpsLocation gps_location = 3;</code>
   * @return Whether the gpsLocation field is set.
   */
  boolean hasGpsLocation();
  /**
   * <code>.server.GpsLocation gps_location = 3;</code>
   * @return The gpsLocation.
   */
  com.halloapp.proto.server.GpsLocation getGpsLocation();
}
