// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.ReverseGeocodeRequest}
 */
public  final class ReverseGeocodeRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ReverseGeocodeRequest, ReverseGeocodeRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:server.ReverseGeocodeRequest)
    ReverseGeocodeRequestOrBuilder {
  private ReverseGeocodeRequest() {
  }
  public static final int LOCATION_FIELD_NUMBER = 1;
  private com.halloapp.proto.server.GpsLocation location_;
  /**
   * <code>.server.GpsLocation location = 1;</code>
   */
  @java.lang.Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.server.GpsLocation location = 1;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.server.GpsLocation getLocation() {
    return location_ == null ? com.halloapp.proto.server.GpsLocation.getDefaultInstance() : location_;
  }
  /**
   * <code>.server.GpsLocation location = 1;</code>
   */
  private void setLocation(com.halloapp.proto.server.GpsLocation value) {
    value.getClass();
  location_ = value;
    
    }
  /**
   * <code>.server.GpsLocation location = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeLocation(com.halloapp.proto.server.GpsLocation value) {
    value.getClass();
  if (location_ != null &&
        location_ != com.halloapp.proto.server.GpsLocation.getDefaultInstance()) {
      location_ =
        com.halloapp.proto.server.GpsLocation.newBuilder(location_).mergeFrom(value).buildPartial();
    } else {
      location_ = value;
    }
    
  }
  /**
   * <code>.server.GpsLocation location = 1;</code>
   */
  private void clearLocation() {  location_ = null;
    
  }

  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ReverseGeocodeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.ReverseGeocodeRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.ReverseGeocodeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.ReverseGeocodeRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ReverseGeocodeRequest)
      com.halloapp.proto.server.ReverseGeocodeRequestOrBuilder {
    // Construct using com.halloapp.proto.server.ReverseGeocodeRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.server.GpsLocation location = 1;</code>
     */
    @java.lang.Override
    public boolean hasLocation() {
      return instance.hasLocation();
    }
    /**
     * <code>.server.GpsLocation location = 1;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.server.GpsLocation getLocation() {
      return instance.getLocation();
    }
    /**
     * <code>.server.GpsLocation location = 1;</code>
     */
    public Builder setLocation(com.halloapp.proto.server.GpsLocation value) {
      copyOnWrite();
      instance.setLocation(value);
      return this;
      }
    /**
     * <code>.server.GpsLocation location = 1;</code>
     */
    public Builder setLocation(
        com.halloapp.proto.server.GpsLocation.Builder builderForValue) {
      copyOnWrite();
      instance.setLocation(builderForValue.build());
      return this;
    }
    /**
     * <code>.server.GpsLocation location = 1;</code>
     */
    public Builder mergeLocation(com.halloapp.proto.server.GpsLocation value) {
      copyOnWrite();
      instance.mergeLocation(value);
      return this;
    }
    /**
     * <code>.server.GpsLocation location = 1;</code>
     */
    public Builder clearLocation() {  copyOnWrite();
      instance.clearLocation();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.ReverseGeocodeRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.ReverseGeocodeRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "location_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.ReverseGeocodeRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.ReverseGeocodeRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.ReverseGeocodeRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.ReverseGeocodeRequest)
  private static final com.halloapp.proto.server.ReverseGeocodeRequest DEFAULT_INSTANCE;
  static {
    ReverseGeocodeRequest defaultInstance = new ReverseGeocodeRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ReverseGeocodeRequest.class, defaultInstance);
  }

  public static com.halloapp.proto.server.ReverseGeocodeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ReverseGeocodeRequest> PARSER;

  public static com.google.protobuf.Parser<ReverseGeocodeRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

