// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface ReverseGeocodeLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.ReverseGeocodeLocation)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.server.GpsLocation location = 2;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.server.GpsLocation location = 2;</code>
   * @return The location.
   */
  com.halloapp.proto.server.GpsLocation getLocation();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string address = 4;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string neighborhood = 5;</code>
   * @return The neighborhood.
   */
  java.lang.String getNeighborhood();
  /**
   * <code>string neighborhood = 5;</code>
   * @return The bytes for neighborhood.
   */
  com.google.protobuf.ByteString
      getNeighborhoodBytes();

  /**
   * <code>string postcode = 6;</code>
   * @return The postcode.
   */
  java.lang.String getPostcode();
  /**
   * <code>string postcode = 6;</code>
   * @return The bytes for postcode.
   */
  com.google.protobuf.ByteString
      getPostcodeBytes();

  /**
   * <code>string district = 7;</code>
   * @return The district.
   */
  java.lang.String getDistrict();
  /**
   * <code>string district = 7;</code>
   * @return The bytes for district.
   */
  com.google.protobuf.ByteString
      getDistrictBytes();

  /**
   * <code>string region = 8;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 8;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <code>string country = 9;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 9;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string place = 10;</code>
   * @return The place.
   */
  java.lang.String getPlace();
  /**
   * <code>string place = 10;</code>
   * @return The bytes for place.
   */
  com.google.protobuf.ByteString
      getPlaceBytes();
}
