// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface SenderStateBundleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.SenderStateBundle)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes enc_sender_state = 1;</code>
   * @return The encSenderState.
   */
  com.google.protobuf.ByteString getEncSenderState();

  /**
   * <code>int64 uid = 2;</code>
   * @return The uid.
   */
  long getUid();
}
