// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.ServerScore}
 */
public  final class ServerScore extends
    com.google.protobuf.GeneratedMessageLite<
        ServerScore, ServerScore.Builder> implements
    // @@protoc_insertion_point(message_implements:server.ServerScore)
    ServerScoreOrBuilder {
  private ServerScore() {
    explanation_ = "";
  }
  public static final int SCORE_FIELD_NUMBER = 1;
  private long score_;
  /**
   * <code>int64 score = 1;</code>
   * @return The score.
   */
  @java.lang.Override
  public long getScore() {
    return score_;
  }
  /**
   * <code>int64 score = 1;</code>
   * @param value The score to set.
   */
  private void setScore(long value) {
    
    score_ = value;
  }
  /**
   * <code>int64 score = 1;</code>
   */
  private void clearScore() {
    
    score_ = 0L;
  }

  public static final int EXPLANATION_FIELD_NUMBER = 2;
  private java.lang.String explanation_;
  /**
   * <code>string explanation = 2;</code>
   * @return The explanation.
   */
  @java.lang.Override
  public java.lang.String getExplanation() {
    return explanation_;
  }
  /**
   * <code>string explanation = 2;</code>
   * @return The bytes for explanation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExplanationBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(explanation_);
  }
  /**
   * <code>string explanation = 2;</code>
   * @param value The explanation to set.
   */
  private void setExplanation(
      java.lang.String value) {
    value.getClass();
  
    explanation_ = value;
  }
  /**
   * <code>string explanation = 2;</code>
   */
  private void clearExplanation() {
    
    explanation_ = getDefaultInstance().getExplanation();
  }
  /**
   * <code>string explanation = 2;</code>
   * @param value The bytes for explanation to set.
   */
  private void setExplanationBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    explanation_ = value.toStringUtf8();
    
  }

  public static com.halloapp.proto.server.ServerScore parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ServerScore parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ServerScore parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.ServerScore parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.ServerScore prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.ServerScore}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.ServerScore, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.ServerScore)
      com.halloapp.proto.server.ServerScoreOrBuilder {
    // Construct using com.halloapp.proto.server.ServerScore.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 score = 1;</code>
     * @return The score.
     */
    @java.lang.Override
    public long getScore() {
      return instance.getScore();
    }
    /**
     * <code>int64 score = 1;</code>
     * @param value The score to set.
     * @return This builder for chaining.
     */
    public Builder setScore(long value) {
      copyOnWrite();
      instance.setScore(value);
      return this;
    }
    /**
     * <code>int64 score = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScore() {
      copyOnWrite();
      instance.clearScore();
      return this;
    }

    /**
     * <code>string explanation = 2;</code>
     * @return The explanation.
     */
    @java.lang.Override
    public java.lang.String getExplanation() {
      return instance.getExplanation();
    }
    /**
     * <code>string explanation = 2;</code>
     * @return The bytes for explanation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExplanationBytes() {
      return instance.getExplanationBytes();
    }
    /**
     * <code>string explanation = 2;</code>
     * @param value The explanation to set.
     * @return This builder for chaining.
     */
    public Builder setExplanation(
        java.lang.String value) {
      copyOnWrite();
      instance.setExplanation(value);
      return this;
    }
    /**
     * <code>string explanation = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExplanation() {
      copyOnWrite();
      instance.clearExplanation();
      return this;
    }
    /**
     * <code>string explanation = 2;</code>
     * @param value The bytes for explanation to set.
     * @return This builder for chaining.
     */
    public Builder setExplanationBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExplanationBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.ServerScore)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.ServerScore();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "score_",
            "explanation_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.ServerScore> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.ServerScore.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.ServerScore>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.ServerScore)
  private static final com.halloapp.proto.server.ServerScore DEFAULT_INSTANCE;
  static {
    ServerScore defaultInstance = new ServerScore();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ServerScore.class, defaultInstance);
  }

  public static com.halloapp.proto.server.ServerScore getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerScore> PARSER;

  public static com.google.protobuf.Parser<ServerScore> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

