// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface SetLinkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.SetLinkRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.server.Link link = 1;</code>
   * @return Whether the link field is set.
   */
  boolean hasLink();
  /**
   * <code>.server.Link link = 1;</code>
   * @return The link.
   */
  com.halloapp.proto.server.Link getLink();

  /**
   * <code>.server.SetLinkRequest.Action action = 2;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.server.SetLinkRequest.Action action = 2;</code>
   * @return The action.
   */
  com.halloapp.proto.server.SetLinkRequest.Action getAction();
}
