// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface SuggestedProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.SuggestedProfile)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.server.BasicUserProfile user_profile = 1;</code>
   * @return Whether the userProfile field is set.
   */
  boolean hasUserProfile();
  /**
   * <code>.server.BasicUserProfile user_profile = 1;</code>
   * @return The userProfile.
   */
  com.halloapp.proto.server.BasicUserProfile getUserProfile();

  /**
   * <code>.server.SuggestedProfile.Reason reason = 2;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.server.SuggestedProfile.Reason reason = 2;</code>
   * @return The reason.
   */
  com.halloapp.proto.server.SuggestedProfile.Reason getReason();

  /**
   * <pre>
   * Lower rank is better.
   * </pre>
   *
   * <code>int32 rank = 3;</code>
   * @return The rank.
   */
  int getRank();
}
