// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface UploadAvatarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.UploadAvatar)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [deprecated = true];</code>
   * @deprecated server.UploadAvatar.id is deprecated.
   *     See server.proto;l=14
   * @return The id.
   */
  @java.lang.Deprecated java.lang.String getId();
  /**
   * <code>string id = 1 [deprecated = true];</code>
   * @deprecated server.UploadAvatar.id is deprecated.
   *     See server.proto;l=14
   * @return The bytes for id.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * scaled-down binary jpeg data.
   * </pre>
   *
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   * full binary jpeg data.
   * </pre>
   *
   * <code>bytes full_data = 3;</code>
   * @return The fullData.
   */
  com.google.protobuf.ByteString getFullData();
}
