// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

/**
 * Protobuf type {@code server.VerifyOtpResponse}
 */
public  final class VerifyOtpResponse extends
    com.google.protobuf.GeneratedMessageLite<
        VerifyOtpResponse, VerifyOtpResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:server.VerifyOtpResponse)
    VerifyOtpResponseOrBuilder {
  private VerifyOtpResponse() {
    phone_ = "";
    name_ = "";
    groupInviteResult_ = "";
    username_ = "";
  }
  /**
   * Protobuf enum {@code server.VerifyOtpResponse.Result}
   */
  public enum Result
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_RESULT = 0;</code>
     */
    UNKNOWN_RESULT(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>FAILURE = 2;</code>
     */
    FAILURE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_RESULT = 0;</code>
     */
    public static final int UNKNOWN_RESULT_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAILURE = 2;</code>
     */
    public static final int FAILURE_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    public static Result forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_RESULT;
        case 1: return SUCCESS;
        case 2: return FAILURE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            @java.lang.Override
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ResultVerifier.INSTANCE;
    }

    private static final class ResultVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ResultVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Result.forNumber(number) != null;
            }
          };

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.VerifyOtpResponse.Result)
  }

  /**
   * Protobuf enum {@code server.VerifyOtpResponse.Reason}
   */
  public enum Reason
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_REASON = 0;</code>
     */
    UNKNOWN_REASON(0),
    /**
     * <code>INVALID_PHONE_NUMBER = 1;</code>
     */
    INVALID_PHONE_NUMBER(1),
    /**
     * <code>INVALID_CLIENT_VERSION = 2;</code>
     */
    INVALID_CLIENT_VERSION(2),
    /**
     * <code>WRONG_SMS_CODE = 3;</code>
     */
    WRONG_SMS_CODE(3),
    /**
     * <code>MISSING_PHONE = 4;</code>
     */
    MISSING_PHONE(4),
    /**
     * <code>MISSING_CODE = 5;</code>
     */
    MISSING_CODE(5),
    /**
     * <code>MISSING_NAME = 6;</code>
     */
    MISSING_NAME(6),
    /**
     * <code>INVALID_NAME = 7;</code>
     */
    INVALID_NAME(7),
    /**
     * <code>MISSING_IDENTITY_KEY = 8;</code>
     */
    MISSING_IDENTITY_KEY(8),
    /**
     * <code>MISSING_SIGNED_KEY = 9;</code>
     */
    MISSING_SIGNED_KEY(9),
    /**
     * <code>MISSING_ONE_TIME_KEYS = 10;</code>
     */
    MISSING_ONE_TIME_KEYS(10),
    /**
     * <code>BAD_BASE64_KEY = 11;</code>
     */
    BAD_BASE64_KEY(11),
    /**
     * <code>INVALID_ONE_TIME_KEYS = 12;</code>
     */
    INVALID_ONE_TIME_KEYS(12),
    /**
     * <code>TOO_FEW_ONE_TIME_KEYS = 13;</code>
     */
    TOO_FEW_ONE_TIME_KEYS(13),
    /**
     * <code>TOO_MANY_ONE_TIME_KEYS = 14;</code>
     */
    TOO_MANY_ONE_TIME_KEYS(14),
    /**
     * <code>TOO_BIG_IDENTITY_KEY = 15;</code>
     */
    TOO_BIG_IDENTITY_KEY(15),
    /**
     * <code>TOO_BIG_SIGNED_KEY = 16;</code>
     */
    TOO_BIG_SIGNED_KEY(16),
    /**
     * <code>TOO_BIG_ONE_TIME_KEYS = 17;</code>
     */
    TOO_BIG_ONE_TIME_KEYS(17),
    /**
     * <code>INVALID_S_ED_PUB = 18;</code>
     */
    INVALID_S_ED_PUB(18),
    /**
     * <code>INVALID_SIGNED_PHRASE = 19;</code>
     */
    INVALID_SIGNED_PHRASE(19),
    /**
     * <code>UNABLE_TO_OPEN_SIGNED_PHRASE = 20;</code>
     */
    UNABLE_TO_OPEN_SIGNED_PHRASE(20),
    /**
     * <code>BAD_REQUEST = 21;</code>
     */
    BAD_REQUEST(21),
    /**
     * <code>INTERNAL_SERVER_ERROR = 22;</code>
     */
    INTERNAL_SERVER_ERROR(22),
    /**
     * <code>INVALID_COUNTRY_CODE = 23;</code>
     */
    INVALID_COUNTRY_CODE(23),
    /**
     * <code>INVALID_LENGTH = 24;</code>
     */
    INVALID_LENGTH(24),
    /**
     * <code>LINE_TYPE_VOIP = 25;</code>
     */
    LINE_TYPE_VOIP(25),
    /**
     * <code>LINE_TYPE_FIXED = 26;</code>
     */
    LINE_TYPE_FIXED(26),
    /**
     * <code>LINE_TYPE_OTHER = 27;</code>
     */
    LINE_TYPE_OTHER(27),
    /**
     * <code>WRONG_HASHCASH_SOLUTION = 28;</code>
     */
    WRONG_HASHCASH_SOLUTION(28),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_REASON = 0;</code>
     */
    public static final int UNKNOWN_REASON_VALUE = 0;
    /**
     * <code>INVALID_PHONE_NUMBER = 1;</code>
     */
    public static final int INVALID_PHONE_NUMBER_VALUE = 1;
    /**
     * <code>INVALID_CLIENT_VERSION = 2;</code>
     */
    public static final int INVALID_CLIENT_VERSION_VALUE = 2;
    /**
     * <code>WRONG_SMS_CODE = 3;</code>
     */
    public static final int WRONG_SMS_CODE_VALUE = 3;
    /**
     * <code>MISSING_PHONE = 4;</code>
     */
    public static final int MISSING_PHONE_VALUE = 4;
    /**
     * <code>MISSING_CODE = 5;</code>
     */
    public static final int MISSING_CODE_VALUE = 5;
    /**
     * <code>MISSING_NAME = 6;</code>
     */
    public static final int MISSING_NAME_VALUE = 6;
    /**
     * <code>INVALID_NAME = 7;</code>
     */
    public static final int INVALID_NAME_VALUE = 7;
    /**
     * <code>MISSING_IDENTITY_KEY = 8;</code>
     */
    public static final int MISSING_IDENTITY_KEY_VALUE = 8;
    /**
     * <code>MISSING_SIGNED_KEY = 9;</code>
     */
    public static final int MISSING_SIGNED_KEY_VALUE = 9;
    /**
     * <code>MISSING_ONE_TIME_KEYS = 10;</code>
     */
    public static final int MISSING_ONE_TIME_KEYS_VALUE = 10;
    /**
     * <code>BAD_BASE64_KEY = 11;</code>
     */
    public static final int BAD_BASE64_KEY_VALUE = 11;
    /**
     * <code>INVALID_ONE_TIME_KEYS = 12;</code>
     */
    public static final int INVALID_ONE_TIME_KEYS_VALUE = 12;
    /**
     * <code>TOO_FEW_ONE_TIME_KEYS = 13;</code>
     */
    public static final int TOO_FEW_ONE_TIME_KEYS_VALUE = 13;
    /**
     * <code>TOO_MANY_ONE_TIME_KEYS = 14;</code>
     */
    public static final int TOO_MANY_ONE_TIME_KEYS_VALUE = 14;
    /**
     * <code>TOO_BIG_IDENTITY_KEY = 15;</code>
     */
    public static final int TOO_BIG_IDENTITY_KEY_VALUE = 15;
    /**
     * <code>TOO_BIG_SIGNED_KEY = 16;</code>
     */
    public static final int TOO_BIG_SIGNED_KEY_VALUE = 16;
    /**
     * <code>TOO_BIG_ONE_TIME_KEYS = 17;</code>
     */
    public static final int TOO_BIG_ONE_TIME_KEYS_VALUE = 17;
    /**
     * <code>INVALID_S_ED_PUB = 18;</code>
     */
    public static final int INVALID_S_ED_PUB_VALUE = 18;
    /**
     * <code>INVALID_SIGNED_PHRASE = 19;</code>
     */
    public static final int INVALID_SIGNED_PHRASE_VALUE = 19;
    /**
     * <code>UNABLE_TO_OPEN_SIGNED_PHRASE = 20;</code>
     */
    public static final int UNABLE_TO_OPEN_SIGNED_PHRASE_VALUE = 20;
    /**
     * <code>BAD_REQUEST = 21;</code>
     */
    public static final int BAD_REQUEST_VALUE = 21;
    /**
     * <code>INTERNAL_SERVER_ERROR = 22;</code>
     */
    public static final int INTERNAL_SERVER_ERROR_VALUE = 22;
    /**
     * <code>INVALID_COUNTRY_CODE = 23;</code>
     */
    public static final int INVALID_COUNTRY_CODE_VALUE = 23;
    /**
     * <code>INVALID_LENGTH = 24;</code>
     */
    public static final int INVALID_LENGTH_VALUE = 24;
    /**
     * <code>LINE_TYPE_VOIP = 25;</code>
     */
    public static final int LINE_TYPE_VOIP_VALUE = 25;
    /**
     * <code>LINE_TYPE_FIXED = 26;</code>
     */
    public static final int LINE_TYPE_FIXED_VALUE = 26;
    /**
     * <code>LINE_TYPE_OTHER = 27;</code>
     */
    public static final int LINE_TYPE_OTHER_VALUE = 27;
    /**
     * <code>WRONG_HASHCASH_SOLUTION = 28;</code>
     */
    public static final int WRONG_HASHCASH_SOLUTION_VALUE = 28;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Reason valueOf(int value) {
      return forNumber(value);
    }

    public static Reason forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_REASON;
        case 1: return INVALID_PHONE_NUMBER;
        case 2: return INVALID_CLIENT_VERSION;
        case 3: return WRONG_SMS_CODE;
        case 4: return MISSING_PHONE;
        case 5: return MISSING_CODE;
        case 6: return MISSING_NAME;
        case 7: return INVALID_NAME;
        case 8: return MISSING_IDENTITY_KEY;
        case 9: return MISSING_SIGNED_KEY;
        case 10: return MISSING_ONE_TIME_KEYS;
        case 11: return BAD_BASE64_KEY;
        case 12: return INVALID_ONE_TIME_KEYS;
        case 13: return TOO_FEW_ONE_TIME_KEYS;
        case 14: return TOO_MANY_ONE_TIME_KEYS;
        case 15: return TOO_BIG_IDENTITY_KEY;
        case 16: return TOO_BIG_SIGNED_KEY;
        case 17: return TOO_BIG_ONE_TIME_KEYS;
        case 18: return INVALID_S_ED_PUB;
        case 19: return INVALID_SIGNED_PHRASE;
        case 20: return UNABLE_TO_OPEN_SIGNED_PHRASE;
        case 21: return BAD_REQUEST;
        case 22: return INTERNAL_SERVER_ERROR;
        case 23: return INVALID_COUNTRY_CODE;
        case 24: return INVALID_LENGTH;
        case 25: return LINE_TYPE_VOIP;
        case 26: return LINE_TYPE_FIXED;
        case 27: return LINE_TYPE_OTHER;
        case 28: return WRONG_HASHCASH_SOLUTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Reason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Reason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Reason>() {
            @java.lang.Override
            public Reason findValueByNumber(int number) {
              return Reason.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ReasonVerifier.INSTANCE;
    }

    private static final class ReasonVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ReasonVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Reason.forNumber(number) != null;
            }
          };

    private final int value;

    private Reason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.VerifyOtpResponse.Reason)
  }

  public static final int PHONE_FIELD_NUMBER = 1;
  private java.lang.String phone_;
  /**
   * <code>string phone = 1;</code>
   * @return The phone.
   */
  @java.lang.Override
  public java.lang.String getPhone() {
    return phone_;
  }
  /**
   * <code>string phone = 1;</code>
   * @return The bytes for phone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhoneBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(phone_);
  }
  /**
   * <code>string phone = 1;</code>
   * @param value The phone to set.
   */
  private void setPhone(
      java.lang.String value) {
    value.getClass();
  
    phone_ = value;
  }
  /**
   * <code>string phone = 1;</code>
   */
  private void clearPhone() {
    
    phone_ = getDefaultInstance().getPhone();
  }
  /**
   * <code>string phone = 1;</code>
   * @param value The bytes for phone to set.
   */
  private void setPhoneBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    phone_ = value.toStringUtf8();
    
  }

  public static final int UID_FIELD_NUMBER = 2;
  private long uid_;
  /**
   * <code>int64 uid = 2;</code>
   * @return The uid.
   */
  @java.lang.Override
  public long getUid() {
    return uid_;
  }
  /**
   * <code>int64 uid = 2;</code>
   * @param value The uid to set.
   */
  private void setUid(long value) {
    
    uid_ = value;
  }
  /**
   * <code>int64 uid = 2;</code>
   */
  private void clearUid() {
    
    uid_ = 0L;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private java.lang.String name_;
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 3;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 3;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 3;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();
    
  }

  public static final int RESULT_FIELD_NUMBER = 4;
  private int result_;
  /**
   * <code>.server.VerifyOtpResponse.Result result = 4;</code>
   * @return The enum numeric value on the wire for result.
   */
  @java.lang.Override
  public int getResultValue() {
    return result_;
  }
  /**
   * <code>.server.VerifyOtpResponse.Result result = 4;</code>
   * @return The result.
   */
  @java.lang.Override
  public com.halloapp.proto.server.VerifyOtpResponse.Result getResult() {
    com.halloapp.proto.server.VerifyOtpResponse.Result result = com.halloapp.proto.server.VerifyOtpResponse.Result.forNumber(result_);
    return result == null ? com.halloapp.proto.server.VerifyOtpResponse.Result.UNRECOGNIZED : result;
  }
  /**
   * <code>.server.VerifyOtpResponse.Result result = 4;</code>
   * @param value The enum numeric value on the wire for result to set.
   */
  private void setResultValue(int value) {
      result_ = value;
  }
  /**
   * <code>.server.VerifyOtpResponse.Result result = 4;</code>
   * @param value The result to set.
   */
  private void setResult(com.halloapp.proto.server.VerifyOtpResponse.Result value) {
    result_ = value.getNumber();
    
  }
  /**
   * <code>.server.VerifyOtpResponse.Result result = 4;</code>
   */
  private void clearResult() {
    
    result_ = 0;
  }

  public static final int REASON_FIELD_NUMBER = 5;
  private int reason_;
  /**
   * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
   * @return The enum numeric value on the wire for reason.
   */
  @java.lang.Override
  public int getReasonValue() {
    return reason_;
  }
  /**
   * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
   * @return The reason.
   */
  @java.lang.Override
  public com.halloapp.proto.server.VerifyOtpResponse.Reason getReason() {
    com.halloapp.proto.server.VerifyOtpResponse.Reason result = com.halloapp.proto.server.VerifyOtpResponse.Reason.forNumber(reason_);
    return result == null ? com.halloapp.proto.server.VerifyOtpResponse.Reason.UNRECOGNIZED : result;
  }
  /**
   * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
   * @param value The enum numeric value on the wire for reason to set.
   */
  private void setReasonValue(int value) {
      reason_ = value;
  }
  /**
   * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
   * @param value The reason to set.
   */
  private void setReason(com.halloapp.proto.server.VerifyOtpResponse.Reason value) {
    reason_ = value.getNumber();
    
  }
  /**
   * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
   */
  private void clearReason() {
    
    reason_ = 0;
  }

  public static final int GROUP_INVITE_RESULT_FIELD_NUMBER = 6;
  private java.lang.String groupInviteResult_;
  /**
   * <code>string group_invite_result = 6;</code>
   * @return The groupInviteResult.
   */
  @java.lang.Override
  public java.lang.String getGroupInviteResult() {
    return groupInviteResult_;
  }
  /**
   * <code>string group_invite_result = 6;</code>
   * @return The bytes for groupInviteResult.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupInviteResultBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(groupInviteResult_);
  }
  /**
   * <code>string group_invite_result = 6;</code>
   * @param value The groupInviteResult to set.
   */
  private void setGroupInviteResult(
      java.lang.String value) {
    value.getClass();
  
    groupInviteResult_ = value;
  }
  /**
   * <code>string group_invite_result = 6;</code>
   */
  private void clearGroupInviteResult() {
    
    groupInviteResult_ = getDefaultInstance().getGroupInviteResult();
  }
  /**
   * <code>string group_invite_result = 6;</code>
   * @param value The bytes for groupInviteResult to set.
   */
  private void setGroupInviteResultBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    groupInviteResult_ = value.toStringUtf8();
    
  }

  public static final int USERNAME_FIELD_NUMBER = 7;
  private java.lang.String username_;
  /**
   * <code>string username = 7;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 7;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 7;</code>
   * @param value The username to set.
   */
  private void setUsername(
      java.lang.String value) {
    value.getClass();
  
    username_ = value;
  }
  /**
   * <code>string username = 7;</code>
   */
  private void clearUsername() {
    
    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 7;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();
    
  }

  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.server.VerifyOtpResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.server.VerifyOtpResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.VerifyOtpResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.server.VerifyOtpResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.VerifyOtpResponse)
      com.halloapp.proto.server.VerifyOtpResponseOrBuilder {
    // Construct using com.halloapp.proto.server.VerifyOtpResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string phone = 1;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      return instance.getPhone();
    }
    /**
     * <code>string phone = 1;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      return instance.getPhoneBytes();
    }
    /**
     * <code>string phone = 1;</code>
     * @param value The phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhone(
        java.lang.String value) {
      copyOnWrite();
      instance.setPhone(value);
      return this;
    }
    /**
     * <code>string phone = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone() {
      copyOnWrite();
      instance.clearPhone();
      return this;
    }
    /**
     * <code>string phone = 1;</code>
     * @param value The bytes for phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPhoneBytes(value);
      return this;
    }

    /**
     * <code>int64 uid = 2;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return instance.getUid();
    }
    /**
     * <code>int64 uid = 2;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(long value) {
      copyOnWrite();
      instance.setUid(value);
      return this;
    }
    /**
     * <code>int64 uid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      copyOnWrite();
      instance.clearUid();
      return this;
    }

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>.server.VerifyOtpResponse.Result result = 4;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override
    public int getResultValue() {
      return instance.getResultValue();
    }
    /**
     * <code>.server.VerifyOtpResponse.Result result = 4;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResultValue(int value) {
      copyOnWrite();
      instance.setResultValue(value);
      return this;
    }
    /**
     * <code>.server.VerifyOtpResponse.Result result = 4;</code>
     * @return The result.
     */
    @java.lang.Override
    public com.halloapp.proto.server.VerifyOtpResponse.Result getResult() {
      return instance.getResult();
    }
    /**
     * <code>.server.VerifyOtpResponse.Result result = 4;</code>
     * @param value The enum numeric value on the wire for result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(com.halloapp.proto.server.VerifyOtpResponse.Result value) {
      copyOnWrite();
      instance.setResult(value);
      return this;
    }
    /**
     * <code>.server.VerifyOtpResponse.Result result = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }

    /**
     * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
     * @return The enum numeric value on the wire for reason.
     */
    @java.lang.Override
    public int getReasonValue() {
      return instance.getReasonValue();
    }
    /**
     * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonValue(int value) {
      copyOnWrite();
      instance.setReasonValue(value);
      return this;
    }
    /**
     * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
     * @return The reason.
     */
    @java.lang.Override
    public com.halloapp.proto.server.VerifyOtpResponse.Reason getReason() {
      return instance.getReason();
    }
    /**
     * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
     * @param value The enum numeric value on the wire for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(com.halloapp.proto.server.VerifyOtpResponse.Reason value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>.server.VerifyOtpResponse.Reason reason = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }

    /**
     * <code>string group_invite_result = 6;</code>
     * @return The groupInviteResult.
     */
    @java.lang.Override
    public java.lang.String getGroupInviteResult() {
      return instance.getGroupInviteResult();
    }
    /**
     * <code>string group_invite_result = 6;</code>
     * @return The bytes for groupInviteResult.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupInviteResultBytes() {
      return instance.getGroupInviteResultBytes();
    }
    /**
     * <code>string group_invite_result = 6;</code>
     * @param value The groupInviteResult to set.
     * @return This builder for chaining.
     */
    public Builder setGroupInviteResult(
        java.lang.String value) {
      copyOnWrite();
      instance.setGroupInviteResult(value);
      return this;
    }
    /**
     * <code>string group_invite_result = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupInviteResult() {
      copyOnWrite();
      instance.clearGroupInviteResult();
      return this;
    }
    /**
     * <code>string group_invite_result = 6;</code>
     * @param value The bytes for groupInviteResult to set.
     * @return This builder for chaining.
     */
    public Builder setGroupInviteResultBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGroupInviteResultBytes(value);
      return this;
    }

    /**
     * <code>string username = 7;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 7;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 7;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 7;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.VerifyOtpResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.server.VerifyOtpResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "phone_",
            "uid_",
            "name_",
            "result_",
            "reason_",
            "groupInviteResult_",
            "username_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0002" +
              "\u0003\u0208\u0004\f\u0005\f\u0006\u0208\u0007\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.server.VerifyOtpResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.server.VerifyOtpResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.server.VerifyOtpResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.VerifyOtpResponse)
  private static final com.halloapp.proto.server.VerifyOtpResponse DEFAULT_INSTANCE;
  static {
    VerifyOtpResponse defaultInstance = new VerifyOtpResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      VerifyOtpResponse.class, defaultInstance);
  }

  public static com.halloapp.proto.server.VerifyOtpResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<VerifyOtpResponse> PARSER;

  public static com.google.protobuf.Parser<VerifyOtpResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

