// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.halloapp.proto.server;

public interface WebStanzaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.WebStanza)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Used to identify the user. Must be set on every packet exchanged
   * </pre>
   *
   * <code>bytes static_key = 1;</code>
   * @return The staticKey.
   */
  com.google.protobuf.ByteString getStaticKey();

  /**
   * <pre>
   * between mobile and web client.
   * </pre>
   *
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
