// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_events.proto

package com.halloapp.proto.log_events;

public interface EventDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:server.EventData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <pre>
   * client platform `android` or `ios`
   * </pre>
   *
   * <code>.server.Platform platform = 2;</code>
   * @return The enum numeric value on the wire for platform.
   */
  int getPlatformValue();
  /**
   * <pre>
   * client platform `android` or `ios`
   * </pre>
   *
   * <code>.server.Platform platform = 2;</code>
   * @return The platform.
   */
  com.halloapp.proto.log_events.Platform getPlatform();

  /**
   * <pre>
   * client version (eg.`0.94`)
   * </pre>
   *
   * <code>string version = 3;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * client version (eg.`0.94`)
   * </pre>
   *
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * set by server to indicate when event was received
   * </pre>
   *
   * <code>uint64 timestamp_ms = 4;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();

  /**
   * <pre>
   * 2 letter country code
   * </pre>
   *
   * <code>string cc = 5;</code>
   * @return The cc.
   */
  java.lang.String getCc();
  /**
   * <pre>
   * 2 letter country code
   * </pre>
   *
   * <code>string cc = 5;</code>
   * @return The bytes for cc.
   */
  com.google.protobuf.ByteString
      getCcBytes();

  /**
   * <code>.server.MediaUpload media_upload = 10;</code>
   * @return Whether the mediaUpload field is set.
   */
  boolean hasMediaUpload();
  /**
   * <code>.server.MediaUpload media_upload = 10;</code>
   * @return The mediaUpload.
   */
  com.halloapp.proto.log_events.MediaUpload getMediaUpload();

  /**
   * <code>.server.MediaDownload media_download = 11;</code>
   * @return Whether the mediaDownload field is set.
   */
  boolean hasMediaDownload();
  /**
   * <code>.server.MediaDownload media_download = 11;</code>
   * @return The mediaDownload.
   */
  com.halloapp.proto.log_events.MediaDownload getMediaDownload();

  /**
   * <code>.server.MediaComposeLoad media_compose_load = 12;</code>
   * @return Whether the mediaComposeLoad field is set.
   */
  boolean hasMediaComposeLoad();
  /**
   * <code>.server.MediaComposeLoad media_compose_load = 12;</code>
   * @return The mediaComposeLoad.
   */
  com.halloapp.proto.log_events.MediaComposeLoad getMediaComposeLoad();

  /**
   * <code>.server.PushReceived push_received = 13;</code>
   * @return Whether the pushReceived field is set.
   */
  boolean hasPushReceived();
  /**
   * <code>.server.PushReceived push_received = 13;</code>
   * @return The pushReceived.
   */
  com.halloapp.proto.log_events.PushReceived getPushReceived();

  /**
   * <code>.server.DecryptionReport decryption_report = 14;</code>
   * @return Whether the decryptionReport field is set.
   */
  boolean hasDecryptionReport();
  /**
   * <code>.server.DecryptionReport decryption_report = 14;</code>
   * @return The decryptionReport.
   */
  com.halloapp.proto.log_events.DecryptionReport getDecryptionReport();

  /**
   * <code>.server.Permissions permissions = 15;</code>
   * @return Whether the permissions field is set.
   */
  boolean hasPermissions();
  /**
   * <code>.server.Permissions permissions = 15;</code>
   * @return The permissions.
   */
  com.halloapp.proto.log_events.Permissions getPermissions();

  /**
   * <code>.server.MediaObjectDownload media_object_download = 16;</code>
   * @return Whether the mediaObjectDownload field is set.
   */
  boolean hasMediaObjectDownload();
  /**
   * <code>.server.MediaObjectDownload media_object_download = 16;</code>
   * @return The mediaObjectDownload.
   */
  com.halloapp.proto.log_events.MediaObjectDownload getMediaObjectDownload();

  /**
   * <code>.server.GroupDecryptionReport group_decryption_report = 17;</code>
   * @return Whether the groupDecryptionReport field is set.
   */
  boolean hasGroupDecryptionReport();
  /**
   * <code>.server.GroupDecryptionReport group_decryption_report = 17;</code>
   * @return The groupDecryptionReport.
   */
  com.halloapp.proto.log_events.GroupDecryptionReport getGroupDecryptionReport();

  /**
   * <code>.server.Call call = 18;</code>
   * @return Whether the call field is set.
   */
  boolean hasCall();
  /**
   * <code>.server.Call call = 18;</code>
   * @return The call.
   */
  com.halloapp.proto.log_events.Call getCall();

  public com.halloapp.proto.log_events.EventData.EdataCase getEdataCase();
}
