// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_events.proto

package com.halloapp.proto.log_events;

/**
 * Protobuf type {@code server.GroupHistoryReport}
 */
public  final class GroupHistoryReport extends
    com.google.protobuf.GeneratedMessageLite<
        GroupHistoryReport, GroupHistoryReport.Builder> implements
    // @@protoc_insertion_point(message_implements:server.GroupHistoryReport)
    GroupHistoryReportOrBuilder {
  private GroupHistoryReport() {
    gid_ = "";
    originalVersion_ = "";
  }
  /**
   * Protobuf enum {@code server.GroupHistoryReport.Schedule}
   */
  public enum Schedule
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>DAILY = 0;</code>
     */
    DAILY(0),
    /**
     * <code>RESULT_BASED = 1;</code>
     */
    RESULT_BASED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DAILY = 0;</code>
     */
    public static final int DAILY_VALUE = 0;
    /**
     * <code>RESULT_BASED = 1;</code>
     */
    public static final int RESULT_BASED_VALUE = 1;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Schedule valueOf(int value) {
      return forNumber(value);
    }

    public static Schedule forNumber(int value) {
      switch (value) {
        case 0: return DAILY;
        case 1: return RESULT_BASED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Schedule>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Schedule> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Schedule>() {
            @java.lang.Override
            public Schedule findValueByNumber(int number) {
              return Schedule.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ScheduleVerifier.INSTANCE;
    }

    private static final class ScheduleVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ScheduleVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Schedule.forNumber(number) != null;
            }
          };

    private final int value;

    private Schedule(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:server.GroupHistoryReport.Schedule)
  }

  public static final int GID_FIELD_NUMBER = 1;
  private java.lang.String gid_;
  /**
   * <code>string gid = 1;</code>
   * @return The gid.
   */
  @java.lang.Override
  public java.lang.String getGid() {
    return gid_;
  }
  /**
   * <code>string gid = 1;</code>
   * @return The bytes for gid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(gid_);
  }
  /**
   * <code>string gid = 1;</code>
   * @param value The gid to set.
   */
  private void setGid(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    gid_ = value;
  }
  /**
   * <code>string gid = 1;</code>
   */
  private void clearGid() {
    
    gid_ = getDefaultInstance().getGid();
  }
  /**
   * <code>string gid = 1;</code>
   * @param value The bytes for gid to set.
   */
  private void setGidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    gid_ = value.toStringUtf8();
    
  }

  public static final int NUM_EXPECTED_FIELD_NUMBER = 2;
  private int numExpected_;
  /**
   * <code>uint32 num_expected = 2;</code>
   * @return The numExpected.
   */
  @java.lang.Override
  public int getNumExpected() {
    return numExpected_;
  }
  /**
   * <code>uint32 num_expected = 2;</code>
   * @param value The numExpected to set.
   */
  private void setNumExpected(int value) {
    
    numExpected_ = value;
  }
  /**
   * <code>uint32 num_expected = 2;</code>
   */
  private void clearNumExpected() {
    
    numExpected_ = 0;
  }

  public static final int NUM_DECRYPTED_FIELD_NUMBER = 3;
  private int numDecrypted_;
  /**
   * <code>uint32 num_decrypted = 3;</code>
   * @return The numDecrypted.
   */
  @java.lang.Override
  public int getNumDecrypted() {
    return numDecrypted_;
  }
  /**
   * <code>uint32 num_decrypted = 3;</code>
   * @param value The numDecrypted to set.
   */
  private void setNumDecrypted(int value) {
    
    numDecrypted_ = value;
  }
  /**
   * <code>uint32 num_decrypted = 3;</code>
   */
  private void clearNumDecrypted() {
    
    numDecrypted_ = 0;
  }

  public static final int ORIGINAL_VERSION_FIELD_NUMBER = 4;
  private java.lang.String originalVersion_;
  /**
   * <code>string original_version = 4;</code>
   * @return The originalVersion.
   */
  @java.lang.Override
  public java.lang.String getOriginalVersion() {
    return originalVersion_;
  }
  /**
   * <code>string original_version = 4;</code>
   * @return The bytes for originalVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(originalVersion_);
  }
  /**
   * <code>string original_version = 4;</code>
   * @param value The originalVersion to set.
   */
  private void setOriginalVersion(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    originalVersion_ = value;
  }
  /**
   * <code>string original_version = 4;</code>
   */
  private void clearOriginalVersion() {
    
    originalVersion_ = getDefaultInstance().getOriginalVersion();
  }
  /**
   * <code>string original_version = 4;</code>
   * @param value The bytes for originalVersion to set.
   */
  private void setOriginalVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    originalVersion_ = value.toStringUtf8();
    
  }

  public static final int REREQUEST_COUNT_FIELD_NUMBER = 5;
  private int rerequestCount_;
  /**
   * <code>uint32 rerequest_count = 5;</code>
   * @return The rerequestCount.
   */
  @java.lang.Override
  public int getRerequestCount() {
    return rerequestCount_;
  }
  /**
   * <code>uint32 rerequest_count = 5;</code>
   * @param value The rerequestCount to set.
   */
  private void setRerequestCount(int value) {
    
    rerequestCount_ = value;
  }
  /**
   * <code>uint32 rerequest_count = 5;</code>
   */
  private void clearRerequestCount() {
    
    rerequestCount_ = 0;
  }

  public static final int TIME_TAKEN_S_FIELD_NUMBER = 6;
  private int timeTakenS_;
  /**
   * <code>uint32 time_taken_s = 6;</code>
   * @return The timeTakenS.
   */
  @java.lang.Override
  public int getTimeTakenS() {
    return timeTakenS_;
  }
  /**
   * <code>uint32 time_taken_s = 6;</code>
   * @param value The timeTakenS to set.
   */
  private void setTimeTakenS(int value) {
    
    timeTakenS_ = value;
  }
  /**
   * <code>uint32 time_taken_s = 6;</code>
   */
  private void clearTimeTakenS() {
    
    timeTakenS_ = 0;
  }

  public static final int SCHEDULE_FIELD_NUMBER = 7;
  private int schedule_;
  /**
   * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
   * @return The enum numeric value on the wire for schedule.
   */
  @java.lang.Override
  public int getScheduleValue() {
    return schedule_;
  }
  /**
   * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
   * @return The schedule.
   */
  @java.lang.Override
  public com.halloapp.proto.log_events.GroupHistoryReport.Schedule getSchedule() {
    com.halloapp.proto.log_events.GroupHistoryReport.Schedule result = com.halloapp.proto.log_events.GroupHistoryReport.Schedule.forNumber(schedule_);
    return result == null ? com.halloapp.proto.log_events.GroupHistoryReport.Schedule.UNRECOGNIZED : result;
  }
  /**
   * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
   * @param value The enum numeric value on the wire for schedule to set.
   */
  private void setScheduleValue(int value) {
      schedule_ = value;
  }
  /**
   * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
   * @param value The schedule to set.
   */
  private void setSchedule(com.halloapp.proto.log_events.GroupHistoryReport.Schedule value) {
    schedule_ = value.getNumber();
    
  }
  /**
   * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
   */
  private void clearSchedule() {
    
    schedule_ = 0;
  }

  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.log_events.GroupHistoryReport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.log_events.GroupHistoryReport prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code server.GroupHistoryReport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.log_events.GroupHistoryReport, Builder> implements
      // @@protoc_insertion_point(builder_implements:server.GroupHistoryReport)
      com.halloapp.proto.log_events.GroupHistoryReportOrBuilder {
    // Construct using com.halloapp.proto.log_events.GroupHistoryReport.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string gid = 1;</code>
     * @return The gid.
     */
    @java.lang.Override
    public java.lang.String getGid() {
      return instance.getGid();
    }
    /**
     * <code>string gid = 1;</code>
     * @return The bytes for gid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGidBytes() {
      return instance.getGidBytes();
    }
    /**
     * <code>string gid = 1;</code>
     * @param value The gid to set.
     * @return This builder for chaining.
     */
    public Builder setGid(
        java.lang.String value) {
      copyOnWrite();
      instance.setGid(value);
      return this;
    }
    /**
     * <code>string gid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGid() {
      copyOnWrite();
      instance.clearGid();
      return this;
    }
    /**
     * <code>string gid = 1;</code>
     * @param value The bytes for gid to set.
     * @return This builder for chaining.
     */
    public Builder setGidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGidBytes(value);
      return this;
    }

    /**
     * <code>uint32 num_expected = 2;</code>
     * @return The numExpected.
     */
    @java.lang.Override
    public int getNumExpected() {
      return instance.getNumExpected();
    }
    /**
     * <code>uint32 num_expected = 2;</code>
     * @param value The numExpected to set.
     * @return This builder for chaining.
     */
    public Builder setNumExpected(int value) {
      copyOnWrite();
      instance.setNumExpected(value);
      return this;
    }
    /**
     * <code>uint32 num_expected = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumExpected() {
      copyOnWrite();
      instance.clearNumExpected();
      return this;
    }

    /**
     * <code>uint32 num_decrypted = 3;</code>
     * @return The numDecrypted.
     */
    @java.lang.Override
    public int getNumDecrypted() {
      return instance.getNumDecrypted();
    }
    /**
     * <code>uint32 num_decrypted = 3;</code>
     * @param value The numDecrypted to set.
     * @return This builder for chaining.
     */
    public Builder setNumDecrypted(int value) {
      copyOnWrite();
      instance.setNumDecrypted(value);
      return this;
    }
    /**
     * <code>uint32 num_decrypted = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumDecrypted() {
      copyOnWrite();
      instance.clearNumDecrypted();
      return this;
    }

    /**
     * <code>string original_version = 4;</code>
     * @return The originalVersion.
     */
    @java.lang.Override
    public java.lang.String getOriginalVersion() {
      return instance.getOriginalVersion();
    }
    /**
     * <code>string original_version = 4;</code>
     * @return The bytes for originalVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOriginalVersionBytes() {
      return instance.getOriginalVersionBytes();
    }
    /**
     * <code>string original_version = 4;</code>
     * @param value The originalVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setOriginalVersion(value);
      return this;
    }
    /**
     * <code>string original_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalVersion() {
      copyOnWrite();
      instance.clearOriginalVersion();
      return this;
    }
    /**
     * <code>string original_version = 4;</code>
     * @param value The bytes for originalVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOriginalVersionBytes(value);
      return this;
    }

    /**
     * <code>uint32 rerequest_count = 5;</code>
     * @return The rerequestCount.
     */
    @java.lang.Override
    public int getRerequestCount() {
      return instance.getRerequestCount();
    }
    /**
     * <code>uint32 rerequest_count = 5;</code>
     * @param value The rerequestCount to set.
     * @return This builder for chaining.
     */
    public Builder setRerequestCount(int value) {
      copyOnWrite();
      instance.setRerequestCount(value);
      return this;
    }
    /**
     * <code>uint32 rerequest_count = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRerequestCount() {
      copyOnWrite();
      instance.clearRerequestCount();
      return this;
    }

    /**
     * <code>uint32 time_taken_s = 6;</code>
     * @return The timeTakenS.
     */
    @java.lang.Override
    public int getTimeTakenS() {
      return instance.getTimeTakenS();
    }
    /**
     * <code>uint32 time_taken_s = 6;</code>
     * @param value The timeTakenS to set.
     * @return This builder for chaining.
     */
    public Builder setTimeTakenS(int value) {
      copyOnWrite();
      instance.setTimeTakenS(value);
      return this;
    }
    /**
     * <code>uint32 time_taken_s = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeTakenS() {
      copyOnWrite();
      instance.clearTimeTakenS();
      return this;
    }

    /**
     * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
     * @return The enum numeric value on the wire for schedule.
     */
    @java.lang.Override
    public int getScheduleValue() {
      return instance.getScheduleValue();
    }
    /**
     * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
     * @param value The schedule to set.
     * @return This builder for chaining.
     */
    public Builder setScheduleValue(int value) {
      copyOnWrite();
      instance.setScheduleValue(value);
      return this;
    }
    /**
     * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
     * @return The schedule.
     */
    @java.lang.Override
    public com.halloapp.proto.log_events.GroupHistoryReport.Schedule getSchedule() {
      return instance.getSchedule();
    }
    /**
     * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
     * @param value The enum numeric value on the wire for schedule to set.
     * @return This builder for chaining.
     */
    public Builder setSchedule(com.halloapp.proto.log_events.GroupHistoryReport.Schedule value) {
      copyOnWrite();
      instance.setSchedule(value);
      return this;
    }
    /**
     * <code>.server.GroupHistoryReport.Schedule schedule = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchedule() {
      copyOnWrite();
      instance.clearSchedule();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:server.GroupHistoryReport)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.log_events.GroupHistoryReport();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "gid_",
            "numExpected_",
            "numDecrypted_",
            "originalVersion_",
            "rerequestCount_",
            "timeTakenS_",
            "schedule_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u000b" +
              "\u0003\u000b\u0004\u0208\u0005\u000b\u0006\u000b\u0007\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.log_events.GroupHistoryReport> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.log_events.GroupHistoryReport.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.log_events.GroupHistoryReport>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:server.GroupHistoryReport)
  private static final com.halloapp.proto.log_events.GroupHistoryReport DEFAULT_INSTANCE;
  static {
    GroupHistoryReport defaultInstance = new GroupHistoryReport();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GroupHistoryReport.class, defaultInstance);
  }

  public static com.halloapp.proto.log_events.GroupHistoryReport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GroupHistoryReport> PARSER;

  public static com.google.protobuf.Parser<GroupHistoryReport> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

