// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.proto

package com.halloapp.proto.clients;

/**
 * Protobuf type {@code clients.Address}
 */
public  final class Address extends
    com.google.protobuf.GeneratedMessageLite<
        Address, Address.Builder> implements
    // @@protoc_insertion_point(message_implements:clients.Address)
    AddressOrBuilder {
  private Address() {
    formattedAddressLines_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int FORMATTED_ADDRESS_LINES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> formattedAddressLines_;
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @return A list containing the formattedAddressLines.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getFormattedAddressLinesList() {
    return formattedAddressLines_;
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @return The count of formattedAddressLines.
   */
  @java.lang.Override
  public int getFormattedAddressLinesCount() {
    return formattedAddressLines_.size();
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @param index The index of the element to return.
   * @return The formattedAddressLines at the given index.
   */
  @java.lang.Override
  public java.lang.String getFormattedAddressLines(int index) {
    return formattedAddressLines_.get(index);
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the formattedAddressLines at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFormattedAddressLinesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        formattedAddressLines_.get(index));
  }
  private void ensureFormattedAddressLinesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        formattedAddressLines_;  if (!tmp.isModifiable()) {
      formattedAddressLines_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @param index The index to set the value at.
   * @param value The formattedAddressLines to set.
   */
  private void setFormattedAddressLines(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureFormattedAddressLinesIsMutable();
    formattedAddressLines_.set(index, value);
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @param value The formattedAddressLines to add.
   */
  private void addFormattedAddressLines(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureFormattedAddressLinesIsMutable();
    formattedAddressLines_.add(value);
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @param values The formattedAddressLines to add.
   */
  private void addAllFormattedAddressLines(
      java.lang.Iterable<java.lang.String> values) {
    ensureFormattedAddressLinesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, formattedAddressLines_);
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   */
  private void clearFormattedAddressLines() {
    formattedAddressLines_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string formatted_address_lines = 1;</code>
   * @param value The bytes of the formattedAddressLines to add.
   */
  private void addFormattedAddressLinesBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureFormattedAddressLinesIsMutable();
    formattedAddressLines_.add(value.toStringUtf8());
  }

  public static com.halloapp.proto.clients.Address parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.Address parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.Address parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.Address parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.Address parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.Address parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.Address parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.Address parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.clients.Address parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.Address parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.clients.Address parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.Address parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.clients.Address prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code clients.Address}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.clients.Address, Builder> implements
      // @@protoc_insertion_point(builder_implements:clients.Address)
      com.halloapp.proto.clients.AddressOrBuilder {
    // Construct using com.halloapp.proto.clients.Address.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @return A list containing the formattedAddressLines.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getFormattedAddressLinesList() {
      return java.util.Collections.unmodifiableList(
          instance.getFormattedAddressLinesList());
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @return The count of formattedAddressLines.
     */
    @java.lang.Override
    public int getFormattedAddressLinesCount() {
      return instance.getFormattedAddressLinesCount();
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @param index The index of the element to return.
     * @return The formattedAddressLines at the given index.
     */
    @java.lang.Override
    public java.lang.String getFormattedAddressLines(int index) {
      return instance.getFormattedAddressLines(index);
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the formattedAddressLines at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFormattedAddressLinesBytes(int index) {
      return instance.getFormattedAddressLinesBytes(index);
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @param index The index to set the value at.
     * @param value The formattedAddressLines to set.
     * @return This builder for chaining.
     */
    public Builder setFormattedAddressLines(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setFormattedAddressLines(index, value);
      return this;
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @param value The formattedAddressLines to add.
     * @return This builder for chaining.
     */
    public Builder addFormattedAddressLines(
        java.lang.String value) {
      copyOnWrite();
      instance.addFormattedAddressLines(value);
      return this;
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @param values The formattedAddressLines to add.
     * @return This builder for chaining.
     */
    public Builder addAllFormattedAddressLines(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllFormattedAddressLines(values);
      return this;
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormattedAddressLines() {
      copyOnWrite();
      instance.clearFormattedAddressLines();
      return this;
    }
    /**
     * <code>repeated string formatted_address_lines = 1;</code>
     * @param value The bytes of the formattedAddressLines to add.
     * @return This builder for chaining.
     */
    public Builder addFormattedAddressLinesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addFormattedAddressLinesBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clients.Address)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.clients.Address();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "formattedAddressLines_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.clients.Address> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.clients.Address.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.clients.Address>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clients.Address)
  private static final com.halloapp.proto.clients.Address DEFAULT_INSTANCE;
  static {
    Address defaultInstance = new Address();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Address.class, defaultInstance);
  }

  public static com.halloapp.proto.clients.Address getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Address> PARSER;

  public static com.google.protobuf.Parser<Address> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

