// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.proto

package com.halloapp.proto.clients;

/**
 * Protobuf type {@code clients.ChatContainer}
 */
public  final class ChatContainer extends
    com.google.protobuf.GeneratedMessageLite<
        ChatContainer, ChatContainer.Builder> implements
    // @@protoc_insertion_point(message_implements:clients.ChatContainer)
    ChatContainerOrBuilder {
  private ChatContainer() {
  }
  private int messageCase_ = 0;
  private java.lang.Object message_;
  public enum MessageCase {
    TEXT(2),
    ALBUM(3),
    CONTACT_CARD(4),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 2: return TEXT;
        case 3: return ALBUM;
        case 4: return CONTACT_CARD;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  private void clearMessage() {
    messageCase_ = 0;
    message_ = null;
  }

  public static final int CONTEXT_FIELD_NUMBER = 1;
  private com.halloapp.proto.clients.ChatContext context_;
  /**
   * <code>.clients.ChatContext context = 1;</code>
   */
  @java.lang.Override
  public boolean hasContext() {
    return context_ != null;
  }
  /**
   * <code>.clients.ChatContext context = 1;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.clients.ChatContext getContext() {
    return context_ == null ? com.halloapp.proto.clients.ChatContext.getDefaultInstance() : context_;
  }
  /**
   * <code>.clients.ChatContext context = 1;</code>
   */
  private void setContext(com.halloapp.proto.clients.ChatContext value) {
    value.getClass();
  context_ = value;
    
    }
  /**
   * <code>.clients.ChatContext context = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeContext(com.halloapp.proto.clients.ChatContext value) {
    value.getClass();
  if (context_ != null &&
        context_ != com.halloapp.proto.clients.ChatContext.getDefaultInstance()) {
      context_ =
        com.halloapp.proto.clients.ChatContext.newBuilder(context_).mergeFrom(value).buildPartial();
    } else {
      context_ = value;
    }
    
  }
  /**
   * <code>.clients.ChatContext context = 1;</code>
   */
  private void clearContext() {  context_ = null;
    
  }

  public static final int TEXT_FIELD_NUMBER = 2;
  /**
   * <code>.clients.Text text = 2;</code>
   */
  @java.lang.Override
  public boolean hasText() {
    return messageCase_ == 2;
  }
  /**
   * <code>.clients.Text text = 2;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.clients.Text getText() {
    if (messageCase_ == 2) {
       return (com.halloapp.proto.clients.Text) message_;
    }
    return com.halloapp.proto.clients.Text.getDefaultInstance();
  }
  /**
   * <code>.clients.Text text = 2;</code>
   */
  private void setText(com.halloapp.proto.clients.Text value) {
    value.getClass();
  message_ = value;
    messageCase_ = 2;
  }
  /**
   * <code>.clients.Text text = 2;</code>
   */
  private void mergeText(com.halloapp.proto.clients.Text value) {
    value.getClass();
  if (messageCase_ == 2 &&
        message_ != com.halloapp.proto.clients.Text.getDefaultInstance()) {
      message_ = com.halloapp.proto.clients.Text.newBuilder((com.halloapp.proto.clients.Text) message_)
          .mergeFrom(value).buildPartial();
    } else {
      message_ = value;
    }
    messageCase_ = 2;
  }
  /**
   * <code>.clients.Text text = 2;</code>
   */
  private void clearText() {
    if (messageCase_ == 2) {
      messageCase_ = 0;
      message_ = null;
    }
  }

  public static final int ALBUM_FIELD_NUMBER = 3;
  /**
   * <code>.clients.Album album = 3;</code>
   */
  @java.lang.Override
  public boolean hasAlbum() {
    return messageCase_ == 3;
  }
  /**
   * <code>.clients.Album album = 3;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.clients.Album getAlbum() {
    if (messageCase_ == 3) {
       return (com.halloapp.proto.clients.Album) message_;
    }
    return com.halloapp.proto.clients.Album.getDefaultInstance();
  }
  /**
   * <code>.clients.Album album = 3;</code>
   */
  private void setAlbum(com.halloapp.proto.clients.Album value) {
    value.getClass();
  message_ = value;
    messageCase_ = 3;
  }
  /**
   * <code>.clients.Album album = 3;</code>
   */
  private void mergeAlbum(com.halloapp.proto.clients.Album value) {
    value.getClass();
  if (messageCase_ == 3 &&
        message_ != com.halloapp.proto.clients.Album.getDefaultInstance()) {
      message_ = com.halloapp.proto.clients.Album.newBuilder((com.halloapp.proto.clients.Album) message_)
          .mergeFrom(value).buildPartial();
    } else {
      message_ = value;
    }
    messageCase_ = 3;
  }
  /**
   * <code>.clients.Album album = 3;</code>
   */
  private void clearAlbum() {
    if (messageCase_ == 3) {
      messageCase_ = 0;
      message_ = null;
    }
  }

  public static final int CONTACT_CARD_FIELD_NUMBER = 4;
  /**
   * <code>.clients.ContactCard contact_card = 4;</code>
   */
  @java.lang.Override
  public boolean hasContactCard() {
    return messageCase_ == 4;
  }
  /**
   * <code>.clients.ContactCard contact_card = 4;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.clients.ContactCard getContactCard() {
    if (messageCase_ == 4) {
       return (com.halloapp.proto.clients.ContactCard) message_;
    }
    return com.halloapp.proto.clients.ContactCard.getDefaultInstance();
  }
  /**
   * <code>.clients.ContactCard contact_card = 4;</code>
   */
  private void setContactCard(com.halloapp.proto.clients.ContactCard value) {
    value.getClass();
  message_ = value;
    messageCase_ = 4;
  }
  /**
   * <code>.clients.ContactCard contact_card = 4;</code>
   */
  private void mergeContactCard(com.halloapp.proto.clients.ContactCard value) {
    value.getClass();
  if (messageCase_ == 4 &&
        message_ != com.halloapp.proto.clients.ContactCard.getDefaultInstance()) {
      message_ = com.halloapp.proto.clients.ContactCard.newBuilder((com.halloapp.proto.clients.ContactCard) message_)
          .mergeFrom(value).buildPartial();
    } else {
      message_ = value;
    }
    messageCase_ = 4;
  }
  /**
   * <code>.clients.ContactCard contact_card = 4;</code>
   */
  private void clearContactCard() {
    if (messageCase_ == 4) {
      messageCase_ = 0;
      message_ = null;
    }
  }

  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatContainer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.ChatContainer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.ChatContainer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.clients.ChatContainer prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code clients.ChatContainer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.clients.ChatContainer, Builder> implements
      // @@protoc_insertion_point(builder_implements:clients.ChatContainer)
      com.halloapp.proto.clients.ChatContainerOrBuilder {
    // Construct using com.halloapp.proto.clients.ChatContainer.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public MessageCase
        getMessageCase() {
      return instance.getMessageCase();
    }

    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }


    /**
     * <code>.clients.ChatContext context = 1;</code>
     */
    @java.lang.Override
    public boolean hasContext() {
      return instance.hasContext();
    }
    /**
     * <code>.clients.ChatContext context = 1;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.clients.ChatContext getContext() {
      return instance.getContext();
    }
    /**
     * <code>.clients.ChatContext context = 1;</code>
     */
    public Builder setContext(com.halloapp.proto.clients.ChatContext value) {
      copyOnWrite();
      instance.setContext(value);
      return this;
      }
    /**
     * <code>.clients.ChatContext context = 1;</code>
     */
    public Builder setContext(
        com.halloapp.proto.clients.ChatContext.Builder builderForValue) {
      copyOnWrite();
      instance.setContext(builderForValue.build());
      return this;
    }
    /**
     * <code>.clients.ChatContext context = 1;</code>
     */
    public Builder mergeContext(com.halloapp.proto.clients.ChatContext value) {
      copyOnWrite();
      instance.mergeContext(value);
      return this;
    }
    /**
     * <code>.clients.ChatContext context = 1;</code>
     */
    public Builder clearContext() {  copyOnWrite();
      instance.clearContext();
      return this;
    }

    /**
     * <code>.clients.Text text = 2;</code>
     */
    @java.lang.Override
    public boolean hasText() {
      return instance.hasText();
    }
    /**
     * <code>.clients.Text text = 2;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.clients.Text getText() {
      return instance.getText();
    }
    /**
     * <code>.clients.Text text = 2;</code>
     */
    public Builder setText(com.halloapp.proto.clients.Text value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>.clients.Text text = 2;</code>
     */
    public Builder setText(
        com.halloapp.proto.clients.Text.Builder builderForValue) {
      copyOnWrite();
      instance.setText(builderForValue.build());
      return this;
    }
    /**
     * <code>.clients.Text text = 2;</code>
     */
    public Builder mergeText(com.halloapp.proto.clients.Text value) {
      copyOnWrite();
      instance.mergeText(value);
      return this;
    }
    /**
     * <code>.clients.Text text = 2;</code>
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }

    /**
     * <code>.clients.Album album = 3;</code>
     */
    @java.lang.Override
    public boolean hasAlbum() {
      return instance.hasAlbum();
    }
    /**
     * <code>.clients.Album album = 3;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.clients.Album getAlbum() {
      return instance.getAlbum();
    }
    /**
     * <code>.clients.Album album = 3;</code>
     */
    public Builder setAlbum(com.halloapp.proto.clients.Album value) {
      copyOnWrite();
      instance.setAlbum(value);
      return this;
    }
    /**
     * <code>.clients.Album album = 3;</code>
     */
    public Builder setAlbum(
        com.halloapp.proto.clients.Album.Builder builderForValue) {
      copyOnWrite();
      instance.setAlbum(builderForValue.build());
      return this;
    }
    /**
     * <code>.clients.Album album = 3;</code>
     */
    public Builder mergeAlbum(com.halloapp.proto.clients.Album value) {
      copyOnWrite();
      instance.mergeAlbum(value);
      return this;
    }
    /**
     * <code>.clients.Album album = 3;</code>
     */
    public Builder clearAlbum() {
      copyOnWrite();
      instance.clearAlbum();
      return this;
    }

    /**
     * <code>.clients.ContactCard contact_card = 4;</code>
     */
    @java.lang.Override
    public boolean hasContactCard() {
      return instance.hasContactCard();
    }
    /**
     * <code>.clients.ContactCard contact_card = 4;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.clients.ContactCard getContactCard() {
      return instance.getContactCard();
    }
    /**
     * <code>.clients.ContactCard contact_card = 4;</code>
     */
    public Builder setContactCard(com.halloapp.proto.clients.ContactCard value) {
      copyOnWrite();
      instance.setContactCard(value);
      return this;
    }
    /**
     * <code>.clients.ContactCard contact_card = 4;</code>
     */
    public Builder setContactCard(
        com.halloapp.proto.clients.ContactCard.Builder builderForValue) {
      copyOnWrite();
      instance.setContactCard(builderForValue.build());
      return this;
    }
    /**
     * <code>.clients.ContactCard contact_card = 4;</code>
     */
    public Builder mergeContactCard(com.halloapp.proto.clients.ContactCard value) {
      copyOnWrite();
      instance.mergeContactCard(value);
      return this;
    }
    /**
     * <code>.clients.ContactCard contact_card = 4;</code>
     */
    public Builder clearContactCard() {
      copyOnWrite();
      instance.clearContactCard();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clients.ChatContainer)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.clients.ChatContainer();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "message_",
            "messageCase_",
            "context_",
            com.halloapp.proto.clients.Text.class,
            com.halloapp.proto.clients.Album.class,
            com.halloapp.proto.clients.ContactCard.class,
          };
          java.lang.String info =
              "\u0000\u0004\u0001\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\t\u0002<\u0000" +
              "\u0003<\u0000\u0004<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.clients.ChatContainer> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.clients.ChatContainer.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.clients.ChatContainer>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clients.ChatContainer)
  private static final com.halloapp.proto.clients.ChatContainer DEFAULT_INSTANCE;
  static {
    ChatContainer defaultInstance = new ChatContainer();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChatContainer.class, defaultInstance);
  }

  public static com.halloapp.proto.clients.ChatContainer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChatContainer> PARSER;

  public static com.google.protobuf.Parser<ChatContainer> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

