// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.halloapp.proto.clients;

/**
 * Protobuf type {@code proto.ChatMessage}
 */
public  final class ChatMessage extends
    com.google.protobuf.GeneratedMessageLite<
        ChatMessage, ChatMessage.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.ChatMessage)
    ChatMessageOrBuilder {
  private ChatMessage() {
    media_ = emptyProtobufList();
    text_ = "";
    feedPostId_ = "";
    mentions_ = emptyProtobufList();
    chatReplyMessageId_ = "";
    chatReplyMessageSenderId_ = "";
  }
  public static final int MEDIA_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.clients.Media> media_;
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.halloapp.proto.clients.Media> getMediaList() {
    return media_;
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  public java.util.List<? extends com.halloapp.proto.clients.MediaOrBuilder> 
      getMediaOrBuilderList() {
    return media_;
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  @java.lang.Override
  public int getMediaCount() {
    return media_.size();
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.clients.Media getMedia(int index) {
    return media_.get(index);
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  public com.halloapp.proto.clients.MediaOrBuilder getMediaOrBuilder(
      int index) {
    return media_.get(index);
  }
  private void ensureMediaIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.clients.Media> tmp = media_;
    if (!tmp.isModifiable()) {
      media_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  private void setMedia(
      int index, com.halloapp.proto.clients.Media value) {
    value.getClass();
  ensureMediaIsMutable();
    media_.set(index, value);
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  private void addMedia(com.halloapp.proto.clients.Media value) {
    value.getClass();
  ensureMediaIsMutable();
    media_.add(value);
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  private void addMedia(
      int index, com.halloapp.proto.clients.Media value) {
    value.getClass();
  ensureMediaIsMutable();
    media_.add(index, value);
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  private void addAllMedia(
      java.lang.Iterable<? extends com.halloapp.proto.clients.Media> values) {
    ensureMediaIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, media_);
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  private void clearMedia() {
    media_ = emptyProtobufList();
  }
  /**
   * <code>repeated .proto.Media media = 1;</code>
   */
  private void removeMedia(int index) {
    ensureMediaIsMutable();
    media_.remove(index);
  }

  public static final int TEXT_FIELD_NUMBER = 2;
  private java.lang.String text_;
  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <code>string text = 2;</code>
   * @param value The text to set.
   */
  private void setText(
      java.lang.String value) {
    value.getClass();
  
    text_ = value;
  }
  /**
   * <code>string text = 2;</code>
   */
  private void clearText() {
    
    text_ = getDefaultInstance().getText();
  }
  /**
   * <code>string text = 2;</code>
   * @param value The bytes for text to set.
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    text_ = value.toStringUtf8();
    
  }

  public static final int FEED_POST_ID_FIELD_NUMBER = 3;
  private java.lang.String feedPostId_;
  /**
   * <code>string feed_post_id = 3;</code>
   * @return The feedPostId.
   */
  @java.lang.Override
  public java.lang.String getFeedPostId() {
    return feedPostId_;
  }
  /**
   * <code>string feed_post_id = 3;</code>
   * @return The bytes for feedPostId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFeedPostIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(feedPostId_);
  }
  /**
   * <code>string feed_post_id = 3;</code>
   * @param value The feedPostId to set.
   */
  private void setFeedPostId(
      java.lang.String value) {
    value.getClass();
  
    feedPostId_ = value;
  }
  /**
   * <code>string feed_post_id = 3;</code>
   */
  private void clearFeedPostId() {
    
    feedPostId_ = getDefaultInstance().getFeedPostId();
  }
  /**
   * <code>string feed_post_id = 3;</code>
   * @param value The bytes for feedPostId to set.
   */
  private void setFeedPostIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    feedPostId_ = value.toStringUtf8();
    
  }

  public static final int FEED_POST_MEDIA_INDEX_FIELD_NUMBER = 4;
  private int feedPostMediaIndex_;
  /**
   * <code>int32 feed_post_media_index = 4;</code>
   * @return The feedPostMediaIndex.
   */
  @java.lang.Override
  public int getFeedPostMediaIndex() {
    return feedPostMediaIndex_;
  }
  /**
   * <code>int32 feed_post_media_index = 4;</code>
   * @param value The feedPostMediaIndex to set.
   */
  private void setFeedPostMediaIndex(int value) {
    
    feedPostMediaIndex_ = value;
  }
  /**
   * <code>int32 feed_post_media_index = 4;</code>
   */
  private void clearFeedPostMediaIndex() {
    
    feedPostMediaIndex_ = 0;
  }

  public static final int MENTIONS_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.clients.Mention> mentions_;
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.halloapp.proto.clients.Mention> getMentionsList() {
    return mentions_;
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  public java.util.List<? extends com.halloapp.proto.clients.MentionOrBuilder> 
      getMentionsOrBuilderList() {
    return mentions_;
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  @java.lang.Override
  public int getMentionsCount() {
    return mentions_.size();
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  @java.lang.Override
  public com.halloapp.proto.clients.Mention getMentions(int index) {
    return mentions_.get(index);
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  public com.halloapp.proto.clients.MentionOrBuilder getMentionsOrBuilder(
      int index) {
    return mentions_.get(index);
  }
  private void ensureMentionsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.halloapp.proto.clients.Mention> tmp = mentions_;
    if (!tmp.isModifiable()) {
      mentions_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  private void setMentions(
      int index, com.halloapp.proto.clients.Mention value) {
    value.getClass();
  ensureMentionsIsMutable();
    mentions_.set(index, value);
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  private void addMentions(com.halloapp.proto.clients.Mention value) {
    value.getClass();
  ensureMentionsIsMutable();
    mentions_.add(value);
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  private void addMentions(
      int index, com.halloapp.proto.clients.Mention value) {
    value.getClass();
  ensureMentionsIsMutable();
    mentions_.add(index, value);
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  private void addAllMentions(
      java.lang.Iterable<? extends com.halloapp.proto.clients.Mention> values) {
    ensureMentionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, mentions_);
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  private void clearMentions() {
    mentions_ = emptyProtobufList();
  }
  /**
   * <code>repeated .proto.Mention mentions = 5;</code>
   */
  private void removeMentions(int index) {
    ensureMentionsIsMutable();
    mentions_.remove(index);
  }

  public static final int CHAT_REPLY_MESSAGE_ID_FIELD_NUMBER = 6;
  private java.lang.String chatReplyMessageId_;
  /**
   * <code>string chat_reply_message_id = 6;</code>
   * @return The chatReplyMessageId.
   */
  @java.lang.Override
  public java.lang.String getChatReplyMessageId() {
    return chatReplyMessageId_;
  }
  /**
   * <code>string chat_reply_message_id = 6;</code>
   * @return The bytes for chatReplyMessageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatReplyMessageIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(chatReplyMessageId_);
  }
  /**
   * <code>string chat_reply_message_id = 6;</code>
   * @param value The chatReplyMessageId to set.
   */
  private void setChatReplyMessageId(
      java.lang.String value) {
    value.getClass();
  
    chatReplyMessageId_ = value;
  }
  /**
   * <code>string chat_reply_message_id = 6;</code>
   */
  private void clearChatReplyMessageId() {
    
    chatReplyMessageId_ = getDefaultInstance().getChatReplyMessageId();
  }
  /**
   * <code>string chat_reply_message_id = 6;</code>
   * @param value The bytes for chatReplyMessageId to set.
   */
  private void setChatReplyMessageIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    chatReplyMessageId_ = value.toStringUtf8();
    
  }

  public static final int CHAT_REPLY_MESSAGE_MEDIA_INDEX_FIELD_NUMBER = 7;
  private int chatReplyMessageMediaIndex_;
  /**
   * <code>int32 chat_reply_message_media_index = 7;</code>
   * @return The chatReplyMessageMediaIndex.
   */
  @java.lang.Override
  public int getChatReplyMessageMediaIndex() {
    return chatReplyMessageMediaIndex_;
  }
  /**
   * <code>int32 chat_reply_message_media_index = 7;</code>
   * @param value The chatReplyMessageMediaIndex to set.
   */
  private void setChatReplyMessageMediaIndex(int value) {
    
    chatReplyMessageMediaIndex_ = value;
  }
  /**
   * <code>int32 chat_reply_message_media_index = 7;</code>
   */
  private void clearChatReplyMessageMediaIndex() {
    
    chatReplyMessageMediaIndex_ = 0;
  }

  public static final int CHAT_REPLY_MESSAGE_SENDER_ID_FIELD_NUMBER = 8;
  private java.lang.String chatReplyMessageSenderId_;
  /**
   * <code>string chat_reply_message_sender_id = 8;</code>
   * @return The chatReplyMessageSenderId.
   */
  @java.lang.Override
  public java.lang.String getChatReplyMessageSenderId() {
    return chatReplyMessageSenderId_;
  }
  /**
   * <code>string chat_reply_message_sender_id = 8;</code>
   * @return The bytes for chatReplyMessageSenderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatReplyMessageSenderIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(chatReplyMessageSenderId_);
  }
  /**
   * <code>string chat_reply_message_sender_id = 8;</code>
   * @param value The chatReplyMessageSenderId to set.
   */
  private void setChatReplyMessageSenderId(
      java.lang.String value) {
    value.getClass();
  
    chatReplyMessageSenderId_ = value;
  }
  /**
   * <code>string chat_reply_message_sender_id = 8;</code>
   */
  private void clearChatReplyMessageSenderId() {
    
    chatReplyMessageSenderId_ = getDefaultInstance().getChatReplyMessageSenderId();
  }
  /**
   * <code>string chat_reply_message_sender_id = 8;</code>
   * @param value The bytes for chatReplyMessageSenderId to set.
   */
  private void setChatReplyMessageSenderIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    chatReplyMessageSenderId_ = value.toStringUtf8();
    
  }

  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.ChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.halloapp.proto.clients.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.halloapp.proto.clients.ChatMessage prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code proto.ChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.halloapp.proto.clients.ChatMessage, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.ChatMessage)
      com.halloapp.proto.clients.ChatMessageOrBuilder {
    // Construct using com.halloapp.proto.clients.ChatMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.halloapp.proto.clients.Media> getMediaList() {
      return java.util.Collections.unmodifiableList(
          instance.getMediaList());
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    @java.lang.Override
    public int getMediaCount() {
      return instance.getMediaCount();
    }/**
     * <code>repeated .proto.Media media = 1;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.clients.Media getMedia(int index) {
      return instance.getMedia(index);
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder setMedia(
        int index, com.halloapp.proto.clients.Media value) {
      copyOnWrite();
      instance.setMedia(index, value);
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder setMedia(
        int index, com.halloapp.proto.clients.Media.Builder builderForValue) {
      copyOnWrite();
      instance.setMedia(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder addMedia(com.halloapp.proto.clients.Media value) {
      copyOnWrite();
      instance.addMedia(value);
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder addMedia(
        int index, com.halloapp.proto.clients.Media value) {
      copyOnWrite();
      instance.addMedia(index, value);
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder addMedia(
        com.halloapp.proto.clients.Media.Builder builderForValue) {
      copyOnWrite();
      instance.addMedia(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder addMedia(
        int index, com.halloapp.proto.clients.Media.Builder builderForValue) {
      copyOnWrite();
      instance.addMedia(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder addAllMedia(
        java.lang.Iterable<? extends com.halloapp.proto.clients.Media> values) {
      copyOnWrite();
      instance.addAllMedia(values);
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder clearMedia() {
      copyOnWrite();
      instance.clearMedia();
      return this;
    }
    /**
     * <code>repeated .proto.Media media = 1;</code>
     */
    public Builder removeMedia(int index) {
      copyOnWrite();
      instance.removeMedia(index);
      return this;
    }

    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <code>string text = 2;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>string text = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <code>string text = 2;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <code>string feed_post_id = 3;</code>
     * @return The feedPostId.
     */
    @java.lang.Override
    public java.lang.String getFeedPostId() {
      return instance.getFeedPostId();
    }
    /**
     * <code>string feed_post_id = 3;</code>
     * @return The bytes for feedPostId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFeedPostIdBytes() {
      return instance.getFeedPostIdBytes();
    }
    /**
     * <code>string feed_post_id = 3;</code>
     * @param value The feedPostId to set.
     * @return This builder for chaining.
     */
    public Builder setFeedPostId(
        java.lang.String value) {
      copyOnWrite();
      instance.setFeedPostId(value);
      return this;
    }
    /**
     * <code>string feed_post_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeedPostId() {
      copyOnWrite();
      instance.clearFeedPostId();
      return this;
    }
    /**
     * <code>string feed_post_id = 3;</code>
     * @param value The bytes for feedPostId to set.
     * @return This builder for chaining.
     */
    public Builder setFeedPostIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFeedPostIdBytes(value);
      return this;
    }

    /**
     * <code>int32 feed_post_media_index = 4;</code>
     * @return The feedPostMediaIndex.
     */
    @java.lang.Override
    public int getFeedPostMediaIndex() {
      return instance.getFeedPostMediaIndex();
    }
    /**
     * <code>int32 feed_post_media_index = 4;</code>
     * @param value The feedPostMediaIndex to set.
     * @return This builder for chaining.
     */
    public Builder setFeedPostMediaIndex(int value) {
      copyOnWrite();
      instance.setFeedPostMediaIndex(value);
      return this;
    }
    /**
     * <code>int32 feed_post_media_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeedPostMediaIndex() {
      copyOnWrite();
      instance.clearFeedPostMediaIndex();
      return this;
    }

    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.halloapp.proto.clients.Mention> getMentionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getMentionsList());
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    @java.lang.Override
    public int getMentionsCount() {
      return instance.getMentionsCount();
    }/**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    @java.lang.Override
    public com.halloapp.proto.clients.Mention getMentions(int index) {
      return instance.getMentions(index);
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder setMentions(
        int index, com.halloapp.proto.clients.Mention value) {
      copyOnWrite();
      instance.setMentions(index, value);
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder setMentions(
        int index, com.halloapp.proto.clients.Mention.Builder builderForValue) {
      copyOnWrite();
      instance.setMentions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder addMentions(com.halloapp.proto.clients.Mention value) {
      copyOnWrite();
      instance.addMentions(value);
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder addMentions(
        int index, com.halloapp.proto.clients.Mention value) {
      copyOnWrite();
      instance.addMentions(index, value);
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder addMentions(
        com.halloapp.proto.clients.Mention.Builder builderForValue) {
      copyOnWrite();
      instance.addMentions(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder addMentions(
        int index, com.halloapp.proto.clients.Mention.Builder builderForValue) {
      copyOnWrite();
      instance.addMentions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder addAllMentions(
        java.lang.Iterable<? extends com.halloapp.proto.clients.Mention> values) {
      copyOnWrite();
      instance.addAllMentions(values);
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder clearMentions() {
      copyOnWrite();
      instance.clearMentions();
      return this;
    }
    /**
     * <code>repeated .proto.Mention mentions = 5;</code>
     */
    public Builder removeMentions(int index) {
      copyOnWrite();
      instance.removeMentions(index);
      return this;
    }

    /**
     * <code>string chat_reply_message_id = 6;</code>
     * @return The chatReplyMessageId.
     */
    @java.lang.Override
    public java.lang.String getChatReplyMessageId() {
      return instance.getChatReplyMessageId();
    }
    /**
     * <code>string chat_reply_message_id = 6;</code>
     * @return The bytes for chatReplyMessageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChatReplyMessageIdBytes() {
      return instance.getChatReplyMessageIdBytes();
    }
    /**
     * <code>string chat_reply_message_id = 6;</code>
     * @param value The chatReplyMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setChatReplyMessageId(
        java.lang.String value) {
      copyOnWrite();
      instance.setChatReplyMessageId(value);
      return this;
    }
    /**
     * <code>string chat_reply_message_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatReplyMessageId() {
      copyOnWrite();
      instance.clearChatReplyMessageId();
      return this;
    }
    /**
     * <code>string chat_reply_message_id = 6;</code>
     * @param value The bytes for chatReplyMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setChatReplyMessageIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChatReplyMessageIdBytes(value);
      return this;
    }

    /**
     * <code>int32 chat_reply_message_media_index = 7;</code>
     * @return The chatReplyMessageMediaIndex.
     */
    @java.lang.Override
    public int getChatReplyMessageMediaIndex() {
      return instance.getChatReplyMessageMediaIndex();
    }
    /**
     * <code>int32 chat_reply_message_media_index = 7;</code>
     * @param value The chatReplyMessageMediaIndex to set.
     * @return This builder for chaining.
     */
    public Builder setChatReplyMessageMediaIndex(int value) {
      copyOnWrite();
      instance.setChatReplyMessageMediaIndex(value);
      return this;
    }
    /**
     * <code>int32 chat_reply_message_media_index = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatReplyMessageMediaIndex() {
      copyOnWrite();
      instance.clearChatReplyMessageMediaIndex();
      return this;
    }

    /**
     * <code>string chat_reply_message_sender_id = 8;</code>
     * @return The chatReplyMessageSenderId.
     */
    @java.lang.Override
    public java.lang.String getChatReplyMessageSenderId() {
      return instance.getChatReplyMessageSenderId();
    }
    /**
     * <code>string chat_reply_message_sender_id = 8;</code>
     * @return The bytes for chatReplyMessageSenderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChatReplyMessageSenderIdBytes() {
      return instance.getChatReplyMessageSenderIdBytes();
    }
    /**
     * <code>string chat_reply_message_sender_id = 8;</code>
     * @param value The chatReplyMessageSenderId to set.
     * @return This builder for chaining.
     */
    public Builder setChatReplyMessageSenderId(
        java.lang.String value) {
      copyOnWrite();
      instance.setChatReplyMessageSenderId(value);
      return this;
    }
    /**
     * <code>string chat_reply_message_sender_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatReplyMessageSenderId() {
      copyOnWrite();
      instance.clearChatReplyMessageSenderId();
      return this;
    }
    /**
     * <code>string chat_reply_message_sender_id = 8;</code>
     * @param value The bytes for chatReplyMessageSenderId to set.
     * @return This builder for chaining.
     */
    public Builder setChatReplyMessageSenderIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChatReplyMessageSenderIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.ChatMessage)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.halloapp.proto.clients.ChatMessage();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "media_",
            com.halloapp.proto.clients.Media.class,
            "text_",
            "feedPostId_",
            "feedPostMediaIndex_",
            "mentions_",
            com.halloapp.proto.clients.Mention.class,
            "chatReplyMessageId_",
            "chatReplyMessageMediaIndex_",
            "chatReplyMessageSenderId_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0000\u0001\b\b\u0000\u0002\u0000\u0001\u001b\u0002\u0208\u0003\u0208" +
              "\u0004\u0004\u0005\u001b\u0006\u0208\u0007\u0004\b\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.halloapp.proto.clients.ChatMessage> parser = PARSER;
        if (parser == null) {
          synchronized (com.halloapp.proto.clients.ChatMessage.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.halloapp.proto.clients.ChatMessage>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.ChatMessage)
  private static final com.halloapp.proto.clients.ChatMessage DEFAULT_INSTANCE;
  static {
    ChatMessage defaultInstance = new ChatMessage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChatMessage.class, defaultInstance);
  }

  public static com.halloapp.proto.clients.ChatMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChatMessage> PARSER;

  public static com.google.protobuf.Parser<ChatMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

