// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.proto

package com.halloapp.proto.clients;

public interface ContactCardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clients.ContactCard)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .clients.Contact contacts = 1;</code>
   */
  java.util.List<com.halloapp.proto.clients.Contact> 
      getContactsList();
  /**
   * <code>repeated .clients.Contact contacts = 1;</code>
   */
  com.halloapp.proto.clients.Contact getContacts(int index);
  /**
   * <code>repeated .clients.Contact contacts = 1;</code>
   */
  int getContactsCount();

  /**
   * <code>.clients.Text text = 2;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>.clients.Text text = 2;</code>
   * @return The text.
   */
  com.halloapp.proto.clients.Text getText();
}
