// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.proto

package com.halloapp.proto.clients;

public interface FilesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clients.Files)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .clients.File files = 1;</code>
   */
  java.util.List<com.halloapp.proto.clients.File> 
      getFilesList();
  /**
   * <code>repeated .clients.File files = 1;</code>
   */
  com.halloapp.proto.clients.File getFiles(int index);
  /**
   * <code>repeated .clients.File files = 1;</code>
   */
  int getFilesCount();

  /**
   * <code>.clients.Text text = 2;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>.clients.Text text = 2;</code>
   * @return The text.
   */
  com.halloapp.proto.clients.Text getText();
}
