// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.proto

package com.halloapp.proto.clients;

public interface PositionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clients.PositionInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
