// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.proto

package com.halloapp.proto.clients;

public interface SenderStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clients.SenderState)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clients.SenderKey sender_key = 1;</code>
   * @return Whether the senderKey field is set.
   */
  boolean hasSenderKey();
  /**
   * <code>.clients.SenderKey sender_key = 1;</code>
   * @return The senderKey.
   */
  com.halloapp.proto.clients.SenderKey getSenderKey();

  /**
   * <code>int32 current_chain_index = 2;</code>
   * @return The currentChainIndex.
   */
  int getCurrentChainIndex();
}
