// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clients.proto

package com.halloapp.proto.clients;

public interface VoiceNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clients.VoiceNote)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.clients.EncryptedResource audio = 1;</code>
   * @return Whether the audio field is set.
   */
  boolean hasAudio();
  /**
   * <code>.clients.EncryptedResource audio = 1;</code>
   * @return The audio.
   */
  com.halloapp.proto.clients.EncryptedResource getAudio();
}
