// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web.proto

package com.halloapp.proto.web;

public interface WebContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:web.WebContainer)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.web.FeedRequest feed_request = 1;</code>
   * @return Whether the feedRequest field is set.
   */
  boolean hasFeedRequest();
  /**
   * <code>.web.FeedRequest feed_request = 1;</code>
   * @return The feedRequest.
   */
  com.halloapp.proto.web.FeedRequest getFeedRequest();

  /**
   * <code>.web.FeedResponse feed_response = 2;</code>
   * @return Whether the feedResponse field is set.
   */
  boolean hasFeedResponse();
  /**
   * <code>.web.FeedResponse feed_response = 2;</code>
   * @return The feedResponse.
   */
  com.halloapp.proto.web.FeedResponse getFeedResponse();

  public com.halloapp.proto.web.WebContainer.PayloadCase getPayloadCase();
}
